In [1]:
import os
import re
import glob
import numpy as np
import pandas as pd

In [ ]:
# Pandas :: view ALL
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [ ]:
# Pandas :: Default view
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

In [5]:
# Defines
def analyse_dataframe(df):
    nan_cnt = df.isnull().sum()
    nan_rto = df.isnull().mean()*100
    unique_vals_cnt = df.nunique()

    ana_result = pd.DataFrame({
        'NaN Counts' : nan_cnt
        , 'NaN Ratio (%)' : nan_rto
        , 'Unique Values' : unique_vals_cnt
    })
    return ana_result

In [6]:
# PRE

TXT_DIR  = r"C:\Users\user\Documents\MATLAB\wfu_results\ROI_txt"
NII_DIR  = r"D:\JHAhn\8641_conductivity\8641_CDT-CDT_ex-CDT_in\CDT_unZip\HFC"

ORGANS_ORDER = [
    "Amygdala", "Hippocampus", "Insula", "MTG",
    "ParaHippocampus", "Thalamus", "CC", "Precuneus"
]
SIDE_ORDER = ["LT", "RT", "Whole"]
COND_ORDER = ["HFC", "IC", "EC"]

In [7]:
pattern = re.compile(r"^(HFC|IC|EC)_(LT|RT|Whole)_(.+)\.txt$", re.I)
col_data = {}   # {col_name: Series}

for fp in glob.glob(os.path.join(TXT_DIR, "*.txt")):
    name = os.path.basename(fp)
    m = pattern.match(name)
    if not m:
        raise ValueError(f"파일명 패턴 불일치: {name}")

    cond, side, organ = m.group(1), m.group(2), m.group(3)
    cond, side = cond.upper(), side  # cond만 대문자로 고정
    organ = organ.replace(" ", "")   # 공백이 있으면 제거

    # 274행 검증
    s = pd.read_csv(fp, header=None).squeeze("columns")
    if len(s) != 274:
        raise ValueError(f"행 수(274) 불일치: {name} → {len(s)}행")

    col_name = f"{cond}_{side}_{organ}"
    col_data[col_name] = s

df = pd.DataFrame(col_data)
col_data

ValueError: 행 수(274) 불일치: EC_LT_Amygdala.txt → 10행

In [12]:
expected_cols = []
for side in SIDE_ORDER:
    for organ in ORGANS_ORDER:
        for cond in COND_ORDER:
            cname = f"{cond}_{side}_{organ}"
            if cname in df.columns:
                expected_cols.append(cname)

# 누락 또는 여분 점검
missing = [c for c in expected_cols if c not in df.columns]
extra   = [c for c in df.columns if c not in expected_cols]
if missing:
    raise ValueError(f": {missing}")
if extra:
    expected_cols += extra

df = df[expected_cols]
df

,HFC_LT_Amygdala,IC_LT_Amygdala,EC_LT_Amygdala,HFC_LT_Hippocampus,IC_LT_Hippocampus,EC_LT_Hippocampus,HFC_LT_Insula,IC_LT_Insula,EC_LT_Insula,HFC_LT_MTG,...,EC_RT_ParaHippocampus,HFC_RT_Thalamus,IC_RT_Thalamus,EC_RT_Thalamus,HFC_Whole_CC,IC_Whole_CC,EC_Whole_CC,HFC_Whole_Precuneus,IC_Whole_Precuneus,EC_Whole_Precuneus
0,4.9788860e-01,0.061961,0.410967,0.838401,0.056949,0.556093,0.569074,0.087700,0.498727,0.566726,...,0.543074,0.826938,0.156422,0.670541,0.566084,0.121781,0.444449,0.709944,0.084998,0.624102
1,6.4992461e-01,0.114312,0.539604,0.783283,0.074173,0.619056,0.621108,0.132052,0.516985,0.621009,...,0.556320,1.045575,0.328254,0.717209,0.593882,0.157959,0.435958,0.751718,0.087023,0.667197
2,6.3518651e-01,0.055755,0.537469,0.724749,0.069935,0.650119,0.543414,0.061849,0.511009,0.572327,...,0.560632,1.030501,0.214016,0.816450,0.518856,0.102770,0.416148,0.672717,0.084116,0.586778
3,7.6429523e-01,0.071338,0.592826,0.843046,0.061556,0.595581,0.627041,0.086411,0.603624,0.610571,...,0.610830,0.999321,0.200949,0.798366,0.573783,0.099075,0.474813,0.730034,0.078498,0.647279
4,6.6688490e-01,0.068983,0.614509,0.975962,0.054164,0.751326,0.623509,0.064267,0.627291,0.711997,...,0.602847,0.991634,0.190448,0.801202,0.567557,0.126154,0.441525,0.791421,0.066190,0.727058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,5.6422101e-01,0.077352,0.523213,0.666636,0.090259,0.581154,0.528409,0.100684,0.451361,0.524941,...,0.474700,0.901093,0.220515,0.680470,0.488034,0.144081,0.344001,0.621078,0.117980,0.506970
270,6.9848789e-01,0.133280,0.594502,0.743387,0.105156,0.491800,0.542317,0.154168,0.442211,0.481155,...,0.526787,0.860828,0.222414,0.638332,0.536061,0.155244,0.380953,0.602585,0.118519,0.487089
271,8.3637830e-01,0.075306,0.682050,0.715348,0.075344,0.519286,0.524379,0.093592,0.488558,0.514201,...,0.343942,0.769077,0.179261,0.590332,0.535888,0.157677,0.378221,0.599822,0.092429,0.508567
272,4.9683935e-01,0.090352,0.425914,0.759475,0.112112,0.489371,0.569115,0.132434,0.478665,0.560055,...,0.368515,0.890930,0.280834,0.610054,0.601955,0.208697,0.393320,0.717549,0.149375,0.571504
273,8.0954189e-01,0.137348,0.564982,0.858859,0.172937,0.774020,0.576076,0.134966,0.474099,0.583558,...,0.560762,1.058948,0.334397,0.724455,0.576984,0.219076,0.358024,0.788331,0.139725,0.648481

In [18]:
subject_files = sorted(glob.glob(os.path.join(NII_DIR, "wConduct_*.nii")))
if len(subject_files) != len(df):
    raise ValueError(f"행 수(274)와 .nii 파일 수({len(subject_files)}) 불일치")

extract_code = lambda path: os.path.splitext(os.path.basename(path))[0].split("_", 1)[1]
df.index = [extract_code(p) for p in subject_files]
df.index.name = "PDI"

df

,HFC_LT_Amygdala,IC_LT_Amygdala,EC_LT_Amygdala,HFC_LT_Hippocampus,IC_LT_Hippocampus,EC_LT_Hippocampus,HFC_LT_Insula,IC_LT_Insula,EC_LT_Insula,HFC_LT_MTG,...,EC_RT_ParaHippocampus,HFC_RT_Thalamus,IC_RT_Thalamus,EC_RT_Thalamus,HFC_Whole_CC,IC_Whole_CC,EC_Whole_CC,HFC_Whole_Precuneus,IC_Whole_Precuneus,EC_Whole_Precuneus
PDI,,,,,,,,,,,,,,,,,,,,,
ADEPT01_YSJ_NODDI24,4.9788860e-01,0.061961,0.410967,0.838401,0.056949,0.556093,0.569074,0.087700,0.498727,0.566726,...,0.543074,0.826938,0.156422,0.670541,0.566084,0.121781,0.444449,0.709944,0.084998,0.624102
ADEPT02_LKY_NODDI24,6.4992461e-01,0.114312,0.539604,0.783283,0.074173,0.619056,0.621108,0.132052,0.516985,0.621009,...,0.556320,1.045575,0.328254,0.717209,0.593882,0.157959,0.435958,0.751718,0.087023,0.667197
ADEPT03_YKJ_NODDI24,6.3518651e-01,0.055755,0.537469,0.724749,0.069935,0.650119,0.543414,0.061849,0.511009,0.572327,...,0.560632,1.030501,0.214016,0.816450,0.518856,0.102770,0.416148,0.672717,0.084116,0.586778
ADEPT04_JWS_NODDI24,7.6429523e-01,0.071338,0.592826,0.843046,0.061556,0.595581,0.627041,0.086411,0.603624,0.610571,...,0.610830,0.999321,0.200949,0.798366,0.573783,0.099075,0.474813,0.730034,0.078498,0.647279
ADEPT05_CBK_NODDI24,6.6688490e-01,0.068983,0.614509,0.975962,0.054164,0.751326,0.623509,0.064267,0.627291,0.711997,...,0.602847,0.991634,0.190448,0.801202,0.567557,0.126154,0.441525,0.791421,0.066190,0.727058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MWI_CN82_LMR_NODDI32,5.6422101e-01,0.077352,0.523213,0.666636,0.090259,0.581154,0.528409,0.100684,0.451361,0.524941,...,0.474700,0.901093,0.220515,0.680470,0.488034,0.144081,0.344001,0.621078,0.117980,0.506970
MWI_CN83_LYS_NODDI32,6.9848789e-01,0.133280,0.594502,0.743387,0.105156,0.491800,0.542317,0.154168,0.442211,0.481155,...,0.526787,0.860828,0.222414,0.638332,0.536061,0.155244,0.380953,0.602585,0.118519,0.487089
MWI_CN84_LHS_NODDI32,8.3637830e-01,0.075306,0.682050,0.715348,0.075344,0.519286,0.524379,0.093592,0.488558,0.514201,...,0.343942,0.769077,0.179261,0.590332,0.535888,0.157677,0.378221,0.599822,0.092429,0.508567
VSI41_8550_KDH_NODDI32,4.9683935e-01,0.090352,0.425914,0.759475,0.112112,0.489371,0.569115,0.132434,0.478665,0.560055,...,0.368515,0.890930,0.280834,0.610054,0.601955,0.208697,0.393320,0.717549,0.149375,0.571504
VSI45_8550_KSG_NODDI32,8.0954189e-01,0.137348,0.564982,0.858859,0.172937,0.774020,0.576076,0.134966,0.474099,0.583558,...,0.560762,1.058948,0.334397,0.724455,0.576984,0.219076,0.358024,0.788331,0.139725,0.648481

In [20]:
df.to_excel(os.path.join(TXT_DIR, "ROI_results.xlsx"), index=True)

In [ ]:
## Data Merging below::

In [36]:
dfROI = pd.read_excel(os.path.join(TXT_DIR, "ROI_results.xlsx"), index_col=0)
dfROI

,HFC_LT_Amygdala,IC_LT_Amygdala,EC_LT_Amygdala,HFC_LT_Hippocampus,IC_LT_Hippocampus,EC_LT_Hippocampus,HFC_LT_Insula,IC_LT_Insula,EC_LT_Insula,HFC_LT_MTG,...,EC_RT_ParaHippocampus,HFC_RT_Thalamus,IC_RT_Thalamus,EC_RT_Thalamus,HFC_Whole_CC,IC_Whole_CC,EC_Whole_CC,HFC_Whole_Precuneus,IC_Whole_Precuneus,EC_Whole_Precuneus
PDI,,,,,,,,,,,,,,,,,,,,,
ADEPT01_YSJ_NODDI24,4.9788860e-01,0.061961,0.410967,0.838401,0.056949,0.556093,0.569074,0.087700,0.498727,0.566726,...,0.543074,0.826938,0.156422,0.670541,0.566084,0.121781,0.444449,0.709944,0.084998,0.624102
ADEPT02_LKY_NODDI24,6.4992461e-01,0.114312,0.539604,0.783283,0.074173,0.619056,0.621108,0.132052,0.516985,0.621009,...,0.556320,1.045575,0.328254,0.717209,0.593882,0.157959,0.435958,0.751718,0.087023,0.667197
ADEPT03_YKJ_NODDI24,6.3518651e-01,0.055755,0.537469,0.724749,0.069935,0.650119,0.543414,0.061849,0.511009,0.572327,...,0.560632,1.030501,0.214016,0.816450,0.518856,0.102770,0.416148,0.672717,0.084116,0.586778
ADEPT04_JWS_NODDI24,7.6429523e-01,0.071338,0.592826,0.843046,0.061556,0.595581,0.627041,0.086411,0.603624,0.610571,...,0.610830,0.999321,0.200949,0.798366,0.573783,0.099075,0.474813,0.730034,0.078498,0.647279
ADEPT05_CBK_NODDI24,6.6688490e-01,0.068983,0.614509,0.975962,0.054164,0.751326,0.623509,0.064267,0.627291,0.711997,...,0.602847,0.991634,0.190448,0.801202,0.567557,0.126154,0.441525,0.791421,0.066190,0.727058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MWI_CN82_LMR_NODDI32,5.6422101e-01,0.077352,0.523213,0.666636,0.090259,0.581154,0.528409,0.100684,0.451361,0.524941,...,0.474700,0.901093,0.220515,0.680470,0.488034,0.144081,0.344001,0.621078,0.117980,0.506970
MWI_CN83_LYS_NODDI32,6.9848789e-01,0.133280,0.594502,0.743387,0.105156,0.491800,0.542317,0.154168,0.442211,0.481155,...,0.526787,0.860828,0.222414,0.638332,0.536061,0.155244,0.380953,0.602585,0.118519,0.487089
MWI_CN84_LHS_NODDI32,8.3637830e-01,0.075306,0.682050,0.715348,0.075344,0.519286,0.524379,0.093592,0.488558,0.514201,...,0.343942,0.769077,0.179261,0.590332,0.535888,0.157677,0.378221,0.599822,0.092429,0.508567
VSI41_8550_KDH_NODDI32,4.9683935e-01,0.090352,0.425914,0.759475,0.112112,0.489371,0.569115,0.132434,0.478665,0.560055,...,0.368515,0.890930,0.280834,0.610054,0.601955,0.208697,0.393320,0.717549,0.149375,0.571504
VSI45_8550_KSG_NODDI32,8.0954189e-01,0.137348,0.564982,0.858859,0.172937,0.774020,0.576076,0.134966,0.474099,0.583558,...,0.560762,1.058948,0.334397,0.724455,0.576984,0.219076,0.358024,0.788331,0.139725,0.648481

In [38]:
# Extract before 1st '_'

def keep_until_2nd_underscore_from_right(x: object) -> str:
    parts = str(x).split("_")
    return "_".join(parts[:-2]) if len(parts) >= 3 else parts[0]

dfROI["PDI"] = (
    dfROI.index.to_series()    # Index to Type(Series)
         .map(keep_until_2nd_underscore_from_right)
         .astype("string")
)
roi_cols = [c for c in dfROI.columns if c != 'PDI']
dfROI_sub = dfROI.reset_index(drop=True)[['PDI', *roi_cols]]

dfROI_sub

,PDI,HFC_LT_Amygdala,IC_LT_Amygdala,EC_LT_Amygdala,HFC_LT_Hippocampus,IC_LT_Hippocampus,EC_LT_Hippocampus,HFC_LT_Insula,IC_LT_Insula,EC_LT_Insula,...,EC_RT_ParaHippocampus,HFC_RT_Thalamus,IC_RT_Thalamus,EC_RT_Thalamus,HFC_Whole_CC,IC_Whole_CC,EC_Whole_CC,HFC_Whole_Precuneus,IC_Whole_Precuneus,EC_Whole_Precuneus
0,ADEPT01,4.9788860e-01,0.061961,0.410967,0.838401,0.056949,0.556093,0.569074,0.087700,0.498727,...,0.543074,0.826938,0.156422,0.670541,0.566084,0.121781,0.444449,0.709944,0.084998,0.624102
1,ADEPT02,6.4992461e-01,0.114312,0.539604,0.783283,0.074173,0.619056,0.621108,0.132052,0.516985,...,0.556320,1.045575,0.328254,0.717209,0.593882,0.157959,0.435958,0.751718,0.087023,0.667197
2,ADEPT03,6.3518651e-01,0.055755,0.537469,0.724749,0.069935,0.650119,0.543414,0.061849,0.511009,...,0.560632,1.030501,0.214016,0.816450,0.518856,0.102770,0.416148,0.672717,0.084116,0.586778
3,ADEPT04,7.6429523e-01,0.071338,0.592826,0.843046,0.061556,0.595581,0.627041,0.086411,0.603624,...,0.610830,0.999321,0.200949,0.798366,0.573783,0.099075,0.474813,0.730034,0.078498,0.647279
4,ADEPT05,6.6688490e-01,0.068983,0.614509,0.975962,0.054164,0.751326,0.623509,0.064267,0.627291,...,0.602847,0.991634,0.190448,0.801202,0.567557,0.126154,0.441525,0.791421,0.066190,0.727058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,MWI_CN82,5.6422101e-01,0.077352,0.523213,0.666636,0.090259,0.581154,0.528409,0.100684,0.451361,...,0.474700,0.901093,0.220515,0.680470,0.488034,0.144081,0.344001,0.621078,0.117980,0.506970
270,MWI_CN83,6.9848789e-01,0.133280,0.594502,0.743387,0.105156,0.491800,0.542317,0.154168,0.442211,...,0.526787,0.860828,0.222414,0.638332,0.536061,0.155244,0.380953,0.602585,0.118519,0.487089
271,MWI_CN84,8.3637830e-01,0.075306,0.682050,0.715348,0.075344,0.519286,0.524379,0.093592,0.488558,...,0.343942,0.769077,0.179261,0.590332,0.535888,0.157677,0.378221,0.599822,0.092429,0.508567
272,VSI41_8550,4.9683935e-01,0.090352,0.425914,0.759475,0.112112,0.489371,0.569115,0.132434,0.478665,...,0.368515,0.890930,0.280834,0.610054,0.601955,0.208697,0.393320,0.717549,0.149375,0.571504
273,VSI45_8550,8.0954189e-01,0.137348,0.564982,0.858859,0.172937,0.774020,0.576076,0.134966,0.474099,...,0.560762,1.058948,0.334397,0.724455,0.576984,0.219076,0.358024,0.788331,0.139725,0.648481

In [43]:
ALPS_DIR = r"D:\JHAhn\files"
ALPS_FILE = f"{ALPS_DIR}\Auto_ALPS_index_19-24_M03.xlsx"
dfCN = pd.read_excel(ALPS_FILE, sheet_name='CN')
dfAD = pd.read_excel(ALPS_FILE, sheet_name='Dementia')

def drop_unnamed_columns(df: pd.DataFrame) -> pd.DataFrame:
    return df.loc[:, ~df.columns.str.startswith("Unnamed:")]
dfCN = drop_unnamed_columns(dfCN)
dfAD = drop_unnamed_columns(dfAD)

def drop_after_sgds(df):
    if 'SGDS' not in df.columns:
        raise KeyError("'SGDS' 컬럼을 찾을 수 없습니다.")
    keep_upto = df.columns.get_loc('SGDS')  # SGDS 포함
    return df.iloc[:, :keep_upto + 1]
dfCN = drop_after_sgds(dfCN)
dfAD = drop_after_sgds(dfAD)

print(dfCN.shape, '\n', dfAD.shape)

(58, 62)
 (209, 62)

In [53]:
# ROI keys (df) --> Dict
roi_dict = dfROI_sub.set_index("PDI").to_dict(orient="index")

def match_roi_key(full_pid):
    for key in roi_dict:
        if key in str(full_pid):
            return key
    return None
def attach_roi_partial(df):
    # Find matching key
    df["_roi_key"] = df["PDI"].astype(str).apply(match_roi_key)
    # Filling ROI cols
    roi_cols = list(next(iter(roi_dict.values())).keys())
    for col in roi_cols:
        df[col] = df["_roi_key"].map(
            lambda k: roi_dict[k][col] if k is not None else pd.NA
        )

    return df.drop(columns="_roi_key")

dfCN_mgd = attach_roi_partial(dfCN.copy())
dfAD_mgd = attach_roi_partial(dfAD.copy())

In [54]:
dfCN_mgd

,PDI,PID,DDX,Year,Age,sex,Education_yr,LH-ALL_Dxx_proj,LH-ALL_Dyy_proj,LH-ALL_Dzz_proj,...,EC_RT_ParaHippocampus,HFC_RT_Thalamus,IC_RT_Thalamus,EC_RT_Thalamus,HFC_Whole_CC,IC_Whole_CC,EC_Whole_CC,HFC_Whole_Precuneus,IC_Whole_Precuneus,EC_Whole_Precuneus
0,MWI_CN01_KNH_NODDI32,145616,NL,2019.0,70,F,16.0,0.853582,0.731372,1.259900,...,0.569473,0.826935,0.271682,0.555182,0.596481,0.212770,0.383751,0.628513,0.125133,0.503758
1,MWI_CN04_SSS_NODDI32,2716077,NL,2019.0,62,F,12.0,0.721595,0.654347,1.212313,...,0.489838,0.761443,0.233806,0.527660,0.482623,0.188198,0.294517,0.592590,0.139421,0.453941
2,MWI_CN05_LSS_NODDI32,469852,NL,2019.0,72,M,16.0,0.648850,0.534350,1.036836,...,0.544412,0.850338,0.298828,0.551536,0.560023,0.178677,0.381515,0.707167,0.123957,0.582434
3,MWI_CN06_KDS_NODDI32,2296061,NL,2019.0,72,M,6.0,0.776232,0.855603,0.955848,...,0.573242,1.072521,0.284065,0.788510,0.623203,0.149430,0.473831,0.774144,0.129967,0.644462
4,MWI_CN07_KSB_NODDI32,316024,NL,2019.0,66,M,9.0,0.760503,0.692654,1.243302,...,0.536905,0.884778,0.235095,0.649583,0.540163,0.201650,0.338564,0.664265,0.148808,0.523295
5,MWI_CN09_YKJ_NODDI32,80969,NaMCI,2019.0,65,F,12.0,0.721305,0.585058,1.168966,...,0.545306,0.986288,0.226849,0.759351,0.528989,0.166927,0.362146,0.656091,0.120433,0.535400
6,MWI_CN10_CJS_NODDI32,1147259,Other,2019.0,66,F,9.0,0.766402,0.500861,1.051554,...,0.449067,0.874900,0.364917,0.509969,0.502285,0.193763,0.308677,0.674751,0.154631,0.521590
7,MWI_CN12_LJK_NODDI32,5871888,NL,2019.0,66,F,12.0,0.809517,0.506511,1.159348,...,0.462334,0.860930,0.293146,0.567797,0.561543,0.224490,0.337122,0.663349,0.132673,0.526265
8,MWI_CN13_KH_NODDI32,6476189,SaMCI,2019.0,69,M,16.0,0.661128,0.740881,1.190856,...,0.522063,1.011569,0.237576,0.773883,0.517119,0.085755,0.431430,0.617109,0.129431,0.483453
9,MWI_CN14_PYJ_NODDI32,4341115,NaMCI,2019.0,66,F,0.5,0.667318,0.716731,1.135098,...,0.527500,1.189327,0.276960,0.912264,0.568219,0.154569,0.413899,0.629691,0.130360,0.501892
10,MWI_CN15_YCJ_NODDI32,1607233,Other,2019.0,75,F,6.0,0.783634,0.542104,1.197984,...,0.558958,0.972299,0.285758,0.686471,0.571364,0.164050,0.407373,0.660082,0.112985,0.543710
11,MWI_CN16_LCS_NODDI32,1190888,NaMCI,2019.0,74,M,12.0,0.750492,0.767349,1.155198,...,0.525401,0.972692,0.239256,0.733374,0.567984,0.149137,0.418912,0.704890,0.114604,0.591241
12,MWI_CN17_LPS_NODDI32,4825611,MaMCI,2019.0,63,F,7.0,0.812866,0.996424,1.218665,...,0.480014,0.887022,0.244920,0.642013,0.525424,0.176074,0.349367,0.651993,0.153292,0.501550
13,MWI_CN18_HCS_NODDI32,2022033,MaMCI,2019.0,68,F,6.0,0.805717,0.608529,1.132986,...,0.486360,0.826049,0.303949,0.522080,0.526794,0.191792,0.335063,0.605105,0.134528,0.470944
14,MWI_CN19_CSO_NODDI32,4073053,NL,2019.0,64,F,9.0,0.637047,0.484846,1.023011,...,0.517200,0.867916,0.234691,0.633179,0.473566,0.186737,0.286957,0.652881,0.148644,0.506357
15,MWI_CN20_PYJ_NODDI32,1382411,NL,2020.0,68,M,12.0,0.649847,0.728100,0.978214,...,0.554155,0.865996,0.253210,0.612668,0.566002,0.194978,0.371117,0.668789,0.158707,0.511535
16,MWI_CN21_PYB_NODDI32,4086417,NL,2020.0,66,F,14.0,89.345674,85.156431,85.893714,...,0.463821,0.833821,0.252496,0.581255,0.499714,0.180962,0.318732,0.580333,0.151689,0.433268
17,MWI_CN22_YYJ_NODDI32,875397,NL,2020.0,66,F,16.0,0.771681,0.663884,0.996707,...,0.513835,0.807599,0.227501,0.580202,0.492460,0.184134,0.308399,0.621884,0.129900,0.490079
18,MWI_CN23_HJL_NODDI32,8481071,NL,2020.0,64,F,12.0,0.861621,0.685175,1.368943,...,0.539687,0.925020,0.218422,0.706476,0.469806,0.144857,0.325102,0.593628,0.125361,0.469178
19,MWI_CN24_PKJ_NODDI32,8481058,NL,2020.0,72,M,16.0,0.780769,0.805937,1.189413,...,0.470152,0.945116,0.257279,0.687774,0.453864,0.144097,0.309865,0.666179,0.139076,0.526869
20,MWI_CN25_NKJ_NODDI32,8500417,MaMCI,2020.0,79,F,6.0,0.809053,0.628974,1.200095,...,0.629807,0.956596,0.254913,0.701614,0.634575,0.254143,0.380491,0.701145,0.141241,0.559319
21,MWI_CN26_LSR_NODDI32,8510171,MaMCI,2020.0,69,F,6.0,0.651656,0.516872,1.081359,...,0.462270,0.854853,0.298488,0.556636,0.618233,0.267933,0.350261,0.667676,0.160014,0.509432
22,MWI_CN27_LSJ_NODDI32,8510155,NL,2020.0,68,M,9.0,0.785996,0.609021,1.140311,...,0.501959,0.844196,0.239438,0.604761,0.539841,0.188142,0.351836,0.712939,0.161860,0.556985
23,MWI_CN28_KOS_NODDI32,213101,NL,2020.0,68,F,9.0,0.821979,0.734907,0.993994,...,0.525605,0.852981,0.264995,0.588012,0.550044,0.135748,0.414328,0.672186,0.121256,0.549712
24,MWI_CN29_KSH_NODDI32,243749,SaMCI,2020.0,70,F,12.0,0.652968,0.485778,1.078290,...,0.665788,0.951107,0.317747,0.633336,0.554084,0.151098,0.403054,0.741013,0.150816,0.590936
25,MWI_CN30_PYS_NODDI32,8519137,MaMCI,2020.0,61,F,9.0,0.659945,0.500463,0.978506,...,0.477922,0.836799,0.276130,0.560642,0.485406,0.202200,0.283275,0.625345,0.134644,0.494961
26,MWI_CN31_LOH_NODDI32,2528398,MaMCI,2020.0,75,F,0.0,0.636865,0.624176,1.164440,...,0.497597,0.894365,0.197061,0.697566,0.598659,0.160472,0.438273,0.669564,0.118688,0.554970
27,MWI_CN32_KYH_NODDI32,8664289,SaMCI,2020.0,81,M,9.0,0.696205,0.723061,1.101509,...,0.518186,0.884590,0.273622,0.610941,0.586860,0.148645,0.438361,0.789711,0.150879,0.635681
28,MWI_CN33_LSH_NODDI32,1206895,NL,2020.0,68,F,12.0,0.638877,0.698796,1.098446,...,0.664519,0.911801,0.342418,0.569403,0.516731,0.177462,0.339318,0.643531,0.135235,0.505900
29,MWI_CN34_OJS_NODDI32,4727886,NL,2020.0,77,F,8.0,0.687721,0.524964,1.058712,...,0.551505,1.110993,0.328570,0.782494,0.529869,0.155402,0.374542,0.698818,0.158173,0.541396
30,MWI_CN35_LES_NODDI32,8696493,NL,2020.0,61,F,12.0,0.763828,0.533087,1.089920,...,0.483109,0.737282,0.270293,0.467234,0.530641,0.231312,0.299411,0.644428,0.146404,0.494998
31,MWI_CN36_KER_NODDI32,738146,SaMCI,2020.0,64,F,12.0,0.747137,0.516512,1.174375,...,0.549753,0.842202,0.219193,0.622979,0.518357,0.178988,0.339459,0.626832,0.109305,0.517772
32,MWI_CN37_KJR_NODDI32,1283958,NaMCI,2020.0,65,M,12.0,1.267064,1.244017,1.117839,...,0.454507,0.749496,0.225184,0.524271,0.516256,0.186873,0.329481,0.668951,0.131205,0.540347
33,MWI_CN38_JJB_NODDI32,2022042,NL,2020.0,71,M,3.0,0.697029,0.773143,1.046729,...,0.630026,1.024894,0.292525,0.732272,0.595624,0.129663,0.466013,0.676542,0.109323,0.567562
34,MWI_CN39_LTS_NODDI32,613165,NL,2020.0,77,M,12.0,0.676112,0.748491,1.064096,...,0.507875,0.930561,0.273329,0.657178,0.603205,0.151556,0.451843,0.707243,0.133054,0.575729
35,MWI_CN40_LDS_NODDI32,8129675,NL,2020.0,72,F,12.0,0.680826,0.595489,1.151737,...,0.469159,0.850163,0.383543,0.466574,0.605229,0.194116,0.411091,0.717616,0.147410,0.569150
36,MWI_CN41_JHL_NODDI32,4920375,NL,2020.0,83,F,6.0,0.730996,0.606768,1.137128,...,0.592879,0.840836,0.299190,0.541651,0.623312,0.125874,0.497510,0.775225,0.169911,0.604869
37,MWI_CN57_YHY_NODDI32,8527223,NL,2022.0,76,F,NaN,0.629832,0.574801,0.976331,...,0.508168,0.798943,0.220934,0.578004,0.477151,0.142118,0.335096,0.681972,0.108451,0.580286
38,MWI_CN58_LSB_NODDI32,213324,NL,2022.0,70,M,NaN,0.707732,0.692642,1.101284,...,0.245936,0.840967,0.212460,0.628435,0.535565,0.151260,0.384363,0.636286,0.092683,0.542898
39,MWI_CN61_CHS_NODDI32,1422655,NL,2022.0,76,M,NaN,0.691838,0.513470,1.145116,...,0.518160,0.928442,0.273525,0.655068,0.508125,0.141542,0.366679,0.679949,0.129329,0.544178
40,MWI_CN65_PYS_NODDI32,9524528,NL,2022.0,72,F,NaN,0.742088,0.611022,1.156521,...,0.495931,0.822200,0.190986,0.631176,0.567236,0.182091,0.385219,0.673377,0.123562,0.551009
41,MWI_CN66_CSY_NODDI32,766581,NaMCI,2022.0,71,F,NaN,0.663827,0.725533,1.045238,...,0.436440,0.765378,0.181157,0.584184,0.495296,0.163504,0.331894,0.637991,0.131822,0.508110
42,MWI_CN67_KOS_NODDI32,9577263,NaMCI,2022.0,82,F,NaN,0.625652,0.643337,1.160600,...,0.583334,0.786152,0.203446,0.582679,0.560845,0.146901,0.414069,0.751461,0.115140,0.640286
43,MWI_CN68_CDL_NODDI32,641619,MaMCI,2022.0,74,F,NaN,0.825319,0.661257,1.253624,...,0.546697,0.882832,0.250534,0.632197,0.546445,0.152043,0.394534,0.662188,0.148627,0.512938
44,MWI_CN69_LSL_NODDI32,9588015,NL,2022.0,69,F,NaN,0.567737,0.528092,1.266596,...,0.535490,0.870760,0.208700,0.662040,0.539993,0.129953,0.410144,0.622445,0.123649,0.501116
45,MWI_CN70_LCJ_NODDI32,2202449,NaMCI,2022.0,80,F,NaN,0.771396,0.632500,1.171522,...,0.494867,0.793464,0.218678,0.574741,0.502785,0.165001,0.337965,0.682435,0.120648,0.561929
46,MWI_CN71_LSH_NODDI32,863315,NL,2022.0,73,F,NaN,0.635816,0.511072,1.056698,...,0.629526,0.790673,0.190738,0.600125,0.657349,0.209189,0.448150,0.686114,0.106190,0.578985
47,MWI_CN73_GIS_NODDI32,4074843,MaMCI,2022.0,74,F,NaN,0.614696,0.510977,1.052888,...,0.413912,0.850759,0.284682,0.566028,0.614579,0.217501,0.397129,0.779806,0.171592,0.614299
48,MWI_CN74_LKY_NODDI32,9605724,SaMCI,2022.0,71,F,NaN,0.636038,0.581639,0.989334,...,0.495830,0.807041,0.192684,0.614290,0.540094,0.154422,0.385784,0.672241,0.090988,0.580177
49,MWI_CN75_KKS_NODDI32,9605754,SaMCI,2022.0,73,M,NaN,0.839752,0.745258,1.373741,...,0.457684,0.936529,0.214338,0.722082,0.555994,0.167777,0.388274,0.695768,0.129753,0.565557
50,MWI_CN76_PHJ_NODDI32,359871,NL,2022.0,78,F,NaN,0.974929,0.802987,1.458045,...,0.594984,0.899423,0.214330,0.685096,0.509969,0.174463,0.335585,0.675825,0.164479,0.511178
51,MWI_CN77_PJC_NODDI32,7090169,NL,NaN,68,M,NaN,0.666742,0.643739,1.125764,...,0.434339,0.813729,0.177067,0.636584,0.469045,0.150621,0.318576,0.601623,0.106493,0.492954
52,MWI_CN79_CYE_NODDI32,10412739,SaMCI,2023.0,72,F,NaN,0.753935,0.504262,1.198478,...,0.423002,0.822054,0.257318,0.564671,0.516003,0.183478,0.332622,0.641243,0.138539,0.506524
53,MWI_CN80_LSR_NODDI32,10474812,MaMCI,NaN,78,F,NaN,0.602834,0.559894,1.037194,...,0.753751,0.807771,0.185336,0.622558,0.633271,0.170613,0.462788,0.697514,0.099527,0.591824
54,MWI_CN81_CSH_NODDI32,10482577,SaMCI,2024.0,66,M,NaN,0.638415,0.664246,1.101576,...,0.451643,0.789196,0.212962,0.576243,0.533376,0.141496,0.391933,0.594671,0.095589,0.499690
55,MWI_CN82_LMR_NODDI32,10412747,SaMCI,2023.0,74,M,NaN,0.789849,0.802365,1.201563,...,0.474700,0.901093,0.220515,0.680470,0.488034,0.144081,0.344001,0.621078,0.117980,0.506970
56,MWI_CN83_LYS_NODDI32,10474783,NL,NaN,74,F,NaN,0.572063,0.531833,1.064045,...,0.526787,0.860828,0.222414,0.638332,0.536061,0.155244,0.380953,0.602585,0.118519,0.487089
57,MWI_CN84_LHS_NODDI32,10474798,MaMCI,2024.0,74,F,NaN,0.647483,0.572705,1.053408,...,0.343942,0.769077,0.179261,0.590332,0.535888,0.157677,0.378221,0.599822,0.092429,0.508567

In [55]:
dfAD_mgd

,PDI,PID,DDX,Year,Age,sex,Education_yr,LH-ALL_Dxx_proj,LH-ALL_Dyy_proj,LH-ALL_Dzz_proj,...,EC_RT_ParaHippocampus,HFC_RT_Thalamus,IC_RT_Thalamus,EC_RT_Thalamus,HFC_Whole_CC,IC_Whole_CC,EC_Whole_CC,HFC_Whole_Precuneus,IC_Whole_Precuneus,EC_Whole_Precuneus
0,MREPT2019AD01_KMO_NODDI32,3735478,MaMCI,2019,70.0,F,14.0,0.644891,0.617538,1.173563,...,0.574908,0.836188,0.269571,0.567105,0.589605,0.171864,0.417809,0.673767,0.123427,0.55042
1,MREPT2019AD02_JSJ_NODDI32,4381137,SaMCI,2019,68.0,F,13.0,0.711342,0.473727,1.183256,...,0.523015,0.743879,0.262853,0.481046,0.500492,0.165644,0.334925,0.598505,0.142315,0.457942
2,MREPT2019AD03_OHS_NODDI32,4452316,Other,2019,67.0,F,9.0,0.817484,0.701432,1.253393,...,0.519948,0.885777,0.26201,0.623679,0.528768,0.164828,0.364057,0.579572,0.12915,0.450615
3,MREPT2019AD04_CSY_NODDI32,4681566,Other,2019,66.0,M,12.0,0.636522,0.566616,1.020413,...,0.449734,0.751123,0.223271,0.527847,0.543459,0.2151,0.328426,0.657526,0.129952,0.529767
4,MREPT2019AD05_KJI_NODDI32,7205823,SaMCI,2019,77.0,F,6.0,0.884875,0.763448,1.324970,...,0.516597,0.906839,0.22427,0.682516,0.653884,0.16927,0.484581,0.722335,0.141361,0.584527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,EPT2024AD09_CSO_NODDI32,5212646,Other,2024,79.0,F,NaN,0.777790,0.751147,1.083035,...,0.592709,0.793156,0.242145,0.551257,0.59785,0.143183,0.454816,0.770251,0.122816,0.650285
205,EPT2024AD10_KCJ_NODDI32,7295104,Other,2024,77.0,F,NaN,0.703165,0.449837,1.133783,...,0.360986,0.740868,0.237083,0.503703,0.536423,0.194904,0.341641,0.634578,0.122864,0.507875
206,EPT2024AD11_KHJ_NODDI32,7760856,Other,2024,70.0,F,NaN,0.695299,0.652078,1.204808,...,0.459306,0.886238,0.212521,0.67383,0.583785,0.140967,0.44292,0.638426,0.118866,0.519198
207,EPT2024AD12_LDS_NODDI32,10130501,AD,2024,58.0,M,NaN,0.758654,0.879287,1.034725,...,0.650494,0.910185,0.255858,0.65449,0.624966,0.152604,0.472451,0.771421,0.119155,0.65466
208,EPT2024AD13_LTO_NODDI32,10466131,Other,2024,77.0,F,NaN,0.672885,0.600487,1.233325,...,0.296273,0.809635,0.211624,0.597973,0.638725,0.148933,0.490039,0.712426,0.095413,0.61856

In [59]:
df = dfAD_mgd
for column in df.columns:
    print(f"Col name: {column}")
    print(f"Data type: {df[column].dtype}")
    print(f"Unique values: {len(df[column].unique())}")
    print(df[column].unique())
    print('-'*40)

Col name: PDI
Data type: object
Unique values: 209
['MREPT2019AD01_KMO_NODDI32' 'MREPT2019AD02_JSJ_NODDI32'
 'MREPT2019AD03_OHS_NODDI32' 'MREPT2019AD04_CSY_NODDI32'
 'MREPT2019AD05_KJI_NODDI32' 'MREPT2019AD06_CKJ_NODDI32'
 'MREPT2019AD07_LJH_NODDI32' 'MREPT2019AD09_LKS_NODDI32'
 'MREPT2019AD10_KJL_NODDI32' 'MREPT2019AD11_CKS_NODDI32'
 'MREPT2019AD13_KHS_NODDI32' 'MREPT2019AD14_CMJ_NODDI32'
 'ADEPT01_YSJ_NODDI24' 'ADEPT02_LKY_NODDI24' 'ADEPT03_YKJ_NODDI24'
 'ADEPT04_JWS_NODDI24' 'ADEPT05_CBK_NODDI24' 'ADEPT06_PHJ_NODDI24'
 'ADEPT07_JG_NODDI24' 'ADEPT08_KMJ_NODDI24' 'ADEPT09_JCJ_NODDI24'
 'ADEPT10_YPL_NODDI24' 'ADEPT16_LJS_NODDI24' 'ADEPT18_PST_NODDI24'
 'ADEPT21_CJM_NODDI24' 'ADEPT22_KBS_NODDI24' 'ADEPT23_PYS_NODDI24'
 'ADEPT24_KJH_NODDI24' 'ADEPT25_JKR_NODDI24' 'ADEPT26_KYJ_NODDI24'
 'ADEPT27_KKS_NODDI24' 'ADEPT28_MSH_NODDI24' 'ADEPT29_LBS_NODDI24'
 'ADEPT30_WJS_NODDI24' 'ADEPT31_PTL_NODDI24' 'ADEPT32_KSW_NODDI24'
 'ADEPT33_YCY_NODDI24' 'ADEPT34_PDY_NODDI24' 'ADEPT36_JJS_NODDI24'
 'ADEPT37_KTY_NODDI24' 'ADEPT38_KWW_NODDI24' 'ADEPT39_KKS_NODDI24'
 'ADEPT40_JOS_NODDI24' 'ADEPT41_YBO_NODDI24' 'ADEPT42_PSJ_NODDI24'
 'ADEPT43_SSY_NODDI24' 'ADEPT44_WDS_NODDI24' 'ADEPT45_KKJ_NODDI24'
 'ADEPT46_LJB_NODDI24' 'ADEPT47_SJH_NODDI24' 'ADEPT48_CJK_NODDI24'
 'ADEPT49_LKJ_NODDI24' 'ADEPT50_LJK_NODDI24' 'ADEPT51_HBH_NODDI24'
 'ADEPT52_YCW_NODDI24' 'ADEPT53_PDL_NODDI24' 'ADEPT54_HCS_NODDI24'
 'ADEPT55_HJS_NODDI24' 'ADEPT56_CKJ_NODDI24' 'ADEPT57_LHS_NODDI24'
 'ADEPT58_PJR_NODDI24' 'ADEPT59_KJS_NODDI24' 'ADEPT60_PNS_NODDI24'
 'ADEPT61_YJS_NODDI24' 'ADEPT62_HSO_NODDI24' 'ADEPT63_JMS_NODDI24'
 'ADEPT64_PMS_NODDI24' 'ADEPT65_CMR_NODDI24' 'ADEPT66_LDS_NODDI24'
 'ADEPT67_JKJ_NODDI24' 'HFC2020AD01_KYM_NODDI32' 'HFC2020AD02_KS_NODDI32'
 'MREPT2020AD01_CGS_NODDI32' 'MREPT2020AD02_HMJ_NODDI32'
 'MREPT2020AD03_KJH_NODDI32' 'MREPT2020AD04_NGR_NODDI32'
 'MREPT2020AD05_PJE_NODDI32' 'MREPT2020AD06_JHK_NODDI32'
 'MREPT2020AD07_KYG_NODDI32' 'MREPT2020AD08_CYS_NODDI32'
 'MREPT2020AD09_PJJ_NODDI32' 'MREPT2020AD10_CYJ_NODDI32'
 'MREPT2020AD11_KHJ_NODDI32' 'MREPT2020AD12_KOB_NODDI32'
 'MREPT2020AD13_SBS_NODDI32' 'MREPT2020AD14_CIL_NODDI32'
 'MREPT2020AD15_LHS_NODDI32' 'MREPT2020AD16_CKL_NODDI32'
 'MREPT2020AD17_LSH_NODDI32' 'MREPT2020AD18_YHS_NODDI32'
 'MREPT2020AD20_LSK_NODDI32' 'MREPT2020AD22_KYH_NODDI32'
 'MREPT2020AD23_LSH_NODDI32' 'MREPT2020AD24_YYS_NODDI32'
 'MREPT2020AD25_YSJ_NODDI32' 'MREPT2020AD26_HMH_NODDI32'
 'MREPT2020AD27_YJJ_NODDI32' 'MREPT2020AD28_YYL_NODDI32'
 'HFC2021AD01_YMB_NODDI32' 'HFC2021AD02_SHS_NODDI32'
 'EPT2022AD01_KDKM_NODDI32' 'EPT2022AD02_SKM_NODDI32'
 'EPT2022AD03_KKS_NODDI32' 'EPT2022AD04_KSS_NODDI32'
 'EPT2022AD05_KIJD_NODDI32' 'EPT2022AD063_BPB_NODDI32'
 'EPT2022AD064_LYS_NODDI32' 'EPT2022AD065_CGS_NODDI32'
 'EPT2022AD066_AIS_NODDI32' 'EPT2022AD067_JSO_NODDI32'
 'EPT2022AD068_NSE_NODDI32' 'EPT2022AD069_LBD_NODDI32'
 'EPT2022AD06_JOJ_NODDI32' 'EPT2022AD070_KSH_NODDI32'
 'EPT2022AD071_KSJ_NODDI32' 'EPT2022AD072_SDY_NODDI32'
 'EPT2022AD073_KHR_NODDI32' 'EPT2022AD074_LGR_NODDI32'
 'EPT2022AD07_YMY_NODDI32' 'EPT2022AD08_JIL_NODDI32'
 'EPT2022AD09_JYS_NODDI32' 'EPT2022AD10_HSY_NODDI32'
 'EPT2022AD11_PSI_NODDI32' 'EPT2022AD12_SYS_NODDI32'
 'EPT2022AD13_SYJ_NODDI32' 'EPT2022AD14_PYS_NODDI32'
 'EPT2022AD15_YSH_NODDI32' 'EPT2022AD16_CKJ_NODDI32'
 'EPT2022AD17_KHS_NODDI32' 'EPT2022AD18_PKW_NODDI32'
 'EPT2022AD19_YJH_NODDI32' 'EPT2022AD20_KYS_NODDI32'
 'EPT2022AD21_KOJ_NODDI32' 'EPT2022AD22_NSC_NODDI32'
 'EPT2022AD23_SKSH_NODDI32' 'EPT2022AD24_KJS_NODDI32'
 'EPT2022AD25_KMS_NODDI32' 'EPT2022AD26_PSO_NODDI32'
 'EPT2022AD27_KDS_NODDI32' 'EPT2022AD28_GMS_NODDI32v'
 'EPT2022AD29_LKH_NODDI32' 'EPT2022AD30_NNO_NODDI32'
 'EPT2022AD31_HSB_NODDI32' 'EPT2022AD32_CDR_NODDI32'
 'EPT2022AD33_KTY_NODDI32' 'EPT2022AD34_KMB_NODDI32'
 'EPT2022AD35_HHS_NODDI32' 'EPT2022AD36_JYS_NODDI32'
 'EPT2022AD37_CEH_NODDI32' 'EPT2022AD38_YYS_NODDI32'
 'EPT2022AD39_LJS_NODDI32' 'EPT2022AD40_RKJ_NODDI32'
 'EPT2022AD41_SIJ_NODDI32' 'EPT2022AD42_HPB_NODDI32'
 'EPT2022AD43_CDH_NODDI32' 'EPT2022AD44_LKJ_NODDI32'
 'EPT2022AD45_CHS_NODDI32' 'EPT2022AD46_KOS_NODDI32'
 'EPT2022AD47_KPK_NODDI32' 'EPT2022AD48_HJJ_NODDI32'
 'EPT2022AD49_PCS_NODDI32' 'EPT2022AD50_YYH_NODDI32'
 'EPT2022AD51_KBS_NODDI32' 'EPT2022AD52_POA_NODDI32'
 'EPT2022AD53_KJD_NODDI32' 'EPT2022AD54_GJJ_NODDI32'
 'EPT2022AD55_SSB_NODDI32' 'EPT2022AD56_SKS_NODDI32'
 'EPT2022AD57_KYS_NODDI32' 'EPT2022AD58_PYR_NODDI32'
 'EPT2022AD59_SNO_NODDI32' 'EPT2022AD60_KYD_NODDI32'
 'EPT2022AD61_KYJ_NODDI32' 'EPT2022AD62_LHJ_NODDI32'
 'EPT2023AD01_KMH_NODDI32' 'EPT2023AD02_HUI_NODDI32'
 'EPT2023AD03_MSJ_NODDI32' 'EPT2023AD04_KJU_NODDI32'
 'EPT2023AD05_JIS_NODDI32' 'EPT2023AD06_LSJ_NODDI32'
 'EPT2023AD07_WGJ_NODDI32' 'EPT2023AD08_KMS_NODDI32'
 'EPT2023AD09_LSU_NODDI32' 'EPT2023AD10_JBY_NODDI32'
 'EPT2023AD11_HSY_NODDI32' 'EPT2023AD12_YJS_NODDI32'
 'EPT2023AD13_WOB_NODDI32' 'EPT2023AD14_LMS_NODDI32'
 'EPT2023AD15_LSJ_NODDI32' 'EPT2023AD16_JHG_NODDI32'
 'EPT2023AD17_LHG_NODDI32' 'EPT2023AD18_LMS_NODDI32'
 'EPT2023AD19_KTG_NODDI32' 'EPT2023AD20_CGJ_NODDI32'
 'EPT2023AD21_PDB_NODDI32' 'EPT2023AD22_KID_NODDI32'
 'EPT2024AD01_KJI_NODDI32' 'EPT2024AD02_HUY_NODDI32'
 'EPT2024AD03_NGS_NODDI32' 'EPT2024AD04_LDS_NODDI32'
 'EPT2024AD05_KEJ_NODDI32' 'EPT2024AD06_PYG_NODDI32'
 'EPT2024AD07_JGJ_NODDI32' 'EPT2024AD08_LMS_NODDI32'
 'EPT2024AD09_CSO_NODDI32' 'EPT2024AD10_KCJ_NODDI32'
 'EPT2024AD11_KHJ_NODDI32' 'EPT2024AD12_LDS_NODDI32'
 'EPT2024AD13_LTO_NODDI32']
----------------------------------------
Col name: PID
Data type: int64
Unique values: 208
[ 3735478  4381137  4452316  4681566  7205823  7771796  8079583  1349735
  4569609  5065323  5118195  6762937  6349063   556441  3028284  5430317
  7814522   320473  7400255  7253938   921333  3408262  3260817  6273815
  7548022  7721083  7824705  2423072   872381  3138315  4697696  4615571
   920713  4495624  6307525  7862995  7823239  7858926  7436362  4237986
     5786  5482896   680085  4062186  7922086  3163821   755865  3024048
  7912763  7397337  2394924  1967627  2657475   322738  5433458  3474477
  2459562  7774945  4100729  6033539  3942467  7390313  2537456  8039551
  8086932   628187  2731906  8072285  5465081  5563773  3236196  8808855
  1509705  4738348  4717899  1514027  2671227   129148  8324575  2933875
  5603012  8276845  8365068  8542934  8571878  7843678  3076738   749365
  4662699  4058635  8344895    69764   908575  8700631  8655418  8655425
   577752  5533209    49831   657015   310282   454439   461257   513795
   612238   840132  1083182  1563188  1749412  1881945  2636118  3281139
   710431  3677627  4920903  5244936  7351639  9845319  1246647  1386714
  1468626  1868298  1932252  2603988  2642792  2717687  2986989  3157194
  3417996  3532605  3600925  3633402  3929844  4039744  4600082  5209834
  5216745  5406746  6683962  6916248  7641504  7740365  7816717  7819979
  7835052  8306655  8407468  8584615  8625084  9124745  9295332  9463703
  9468039  9481205  9481613  9491375  9520331  9522162  9572617  9589097
  9589671  9634219  9648051  9648799  9712897  9734851   477555  2065045
  4067051  4301889  4797497  8481752  9682931  9822672  1408745  5282874
  1436161  2345264  4345988  6318811  9076435  8511252  8787368 10228094
  2669298  7953325   235415   672299   672300   915984  1207865  1835793
  3133994  5912132  6763469  1727943  1818063  1934947   463081  2750266
  3691537  4331042  5035723  5212646  7295104  7760856 10130501 10466131]
----------------------------------------
Col name: DDX
Data type: object
Unique values: 7
['MaMCI' 'SaMCI' 'Other' 'AD' 'NaMCI' 'NL' nan]
----------------------------------------
Col name: Year
Data type: int64
Unique values: 6
[2019 2020 2021 2022 2023 2024]
----------------------------------------
Col name: Age
Data type: float64
Unique values: 41
[70. 68. 67. 66. 77. 73. 78. 72. 75. 79. 74. 63. 76. 69. 90. 80. 57. 82.
 81. 86. 71. 83. 61. 85. 89. 54. 51. 60. 84. 96. 87. nan 62. 65. 64. 92.
 50. 40. 88. 91. 58.]
----------------------------------------
Col name: sex
Data type: object
Unique values: 3
['F' 'M' nan]
----------------------------------------
Col name: Education_yr
Data type: float64
Unique values: 19
[14.  13.   9.  12.   6.   nan 16.   7.   4.   5.  18.   0.   0.5  2.
  3.  10.   1.  19.   8. ]
----------------------------------------
Col name: LT_ALL_Dxx_proj
Data type: float64
Unique values: 209
[0.644891 0.711342 0.817484 0.636522 0.884875 0.676956 0.93257  0.614387
 0.71064  0.961293 0.889609 0.514302 0.592921 0.677527 0.713658 0.636028
 0.571027 0.717123 0.653122 0.691966 0.774121 0.75679  0.662992 1.114345
 0.689547 0.590511 0.803339 0.639105 0.907575 0.877886 0.75639  0.773788
 0.663161 0.648225 0.954817 0.865298 0.640273 0.715607 0.735767 0.74697
 0.748909 0.895995 0.720429 0.777927 1.015249 0.781611 0.843801 0.663736
 0.854032 0.842673 0.802067 0.611383 0.84441  0.819996 0.809939 0.937027
 0.745723 0.641687 0.631024 0.781388 0.741792 0.730203 0.744956 0.692357
 0.856909 0.863502 0.745848 0.621174 0.57812  1.01296  1.04424  0.787674
 0.624646 1.006665 0.704174 0.687615 0.830949 0.804617 0.669022 0.558741
 0.567549 0.789869 0.712472 0.558187 0.687167 0.757712 0.634075 0.850102
 0.737843 0.774412 0.608213 0.738897 0.617877 0.744526 0.666114 0.529166
 0.71907  0.99115  0.639082 0.632195 0.687428 0.884833 0.688375 0.720827
 0.687521 0.725325 0.702311 0.687835 1.019929 0.661129 0.682913 0.714135
 0.648407 0.691957 0.848691 0.593003 0.660658 0.773617 0.671343 0.704028
 0.748985 0.721774 0.842524 0.899839 0.647298 0.525954 1.290105 0.621754
 0.581737 0.628854 0.800095 0.685723 0.787983 0.716869 0.735545 0.713494
 0.779564 0.706848 0.672512 0.809665 0.961617 0.70738  0.645374 0.942717
 0.873445 0.713498 0.570495 0.651328 0.662054 0.75147  0.738034 0.776002
 0.716783 0.904237 0.627554 0.709479 0.725724 0.605083 0.676401 0.767485
 0.789217 0.688869 0.76261  0.832842 0.593976 0.667726 0.585434 0.859103
 0.684419 0.752241 0.664335 0.706332 0.690737 0.603933 0.743637 0.649097
 0.787064 0.726438 0.504589 0.823662 0.666029 0.509156 0.726724 0.879091
 0.756672 0.840838 0.633278 0.600937 0.577736 0.903688 0.875751 0.927418
 0.704612 0.667106 0.708895 0.712821 0.560355 0.737402 0.762363 0.609003
 0.849374 0.718001 0.554956 0.870257 0.77779  0.703165 0.695299 0.758654
 0.672885]
----------------------------------------
Col name: LT_ALL_Dyy_proj
Data type: float64
Unique values: 209
[0.617538 0.473727 0.701432 0.566616 0.763448 0.526778 0.760346 0.618671
 0.595827 0.788093 0.946564 0.760812 0.721707 0.608793 0.587548 0.501966
 0.69419  0.654582 0.593881 0.57356  0.599718 0.6805   0.485697 1.13647
 0.690658 0.565186 0.898682 0.57812  0.922679 0.814766 0.66776  0.669394
 0.674745 0.703882 0.996151 0.97801  0.504455 0.611504 0.697976 0.701052
 0.821993 0.87645  0.563148 0.688483 0.767308 0.756681 0.813423 0.621885
 0.797136 0.871819 0.752622 0.627337 0.805356 0.615363 0.739668 0.862638
 0.68161  0.578162 0.581794 0.58581  0.64637  0.838856 0.699794 0.585167
 0.888376 0.656735 0.638285 0.5888   0.607669 1.020676 1.09976  0.617017
 0.630584 1.030653 0.654193 0.664407 0.728287 0.73864  0.743052 0.604754
 0.615347 0.753    0.757548 0.481649 0.82203  0.727023 0.504538 0.671135
 0.573432 0.625499 0.538205 0.769913 0.747627 0.698216 0.466302 0.485423
 0.633371 1.075484 0.570807 0.790451 0.61544  1.023749 0.571691 0.791427
 0.567993 0.690994 0.585001 0.658264 0.993018 0.728565 0.627002 0.681928
 0.544407 0.824765 0.687105 0.49497  0.504997 1.021624 0.669964 0.54911
 0.859231 0.619341 0.789933 0.697691 0.517673 0.562131 1.398008 0.593717
 0.6927   0.606006 0.669203 0.479119 0.672785 0.637086 0.722219 0.583667
 0.591612 0.656015 0.640494 0.810742 0.97116  0.74557  0.704022 0.843918
 0.759741 0.479734 0.658749 0.547181 0.652495 0.788713 0.663406 0.681788
 0.601077 0.718277 0.56842  0.452861 0.651998 0.663665 0.67313  0.84888
 0.863602 0.620125 0.653173 0.739725 0.603444 0.593122 0.617385 0.880303
 0.689697 0.809204 0.648147 0.643079 0.656903 0.5378   0.712603 0.545406
 0.700333 0.620235 0.638047 0.681381 0.674297 0.599337 0.886689 0.847366
 0.801607 0.849529 0.505991 0.617344 0.634232 0.988417 0.801455 1.001147
 0.680323 0.765529 0.816064 0.692009 0.449772 0.674642 0.611719 0.617758
 0.895185 0.722943 0.519521 0.795042 0.751147 0.449837 0.652078 0.879287
 0.600487]
----------------------------------------
Col name: LT_ALL_Dzz_proj
Data type: float64
Unique values: 209
[1.173563 1.183256 1.253393 1.020413 1.32497  1.209016 1.05923  1.152475
 1.16552  1.231277 1.392888 1.054812 0.953535 1.174983 1.225626 1.161122
 0.940595 1.285027 0.933188 1.136913 1.105498 1.139714 1.019973 1.311477
 1.168954 0.991124 1.152376 1.326906 1.544416 1.287628 1.143752 1.072732
 1.083806 1.127048 1.338331 1.111304 0.951965 1.038915 1.253557 1.099733
 1.148538 1.21212  1.020135 1.192634 1.330943 1.285459 1.400683 1.247357
 1.276026 1.184347 0.993692 1.102121 1.229697 1.136695 1.241362 1.351159
 1.205742 1.169518 1.202354 1.188711 1.279406 1.209409 1.304296 1.080796
 1.189395 1.165041 1.188179 1.050407 0.904655 1.411023 1.178006 1.275187
 1.159289 1.433256 1.357517 0.945684 1.208114 1.201483 1.18772  1.166113
 1.129179 1.275562 1.141273 0.95778  1.132069 1.272343 0.954832 1.334508
 1.21977  1.115456 1.186532 1.244719 0.89601  1.384122 1.103041 0.964057
 1.091623 1.367142 1.258236 0.959016 1.088453 1.23767  1.306685 1.263251
 1.001067 1.190966 1.093793 1.200729 1.482874 1.130937 1.170377 1.167826
 1.175009 0.965649 1.266008 1.051231 1.22675  1.241025 1.161513 1.255289
 1.191667 1.139735 1.019088 1.092184 1.203802 1.190894 1.337141 1.120976
 1.234771 0.995007 1.284719 1.101015 1.183734 1.111928 1.295058 1.070543
 1.047948 0.992941 0.888912 1.210563 1.175082 1.081639 1.388936 1.336587
 1.412562 0.990042 1.206562 0.997239 1.211629 1.110113 1.280886 1.246253
 1.086461 1.38513  0.99959  1.214573 1.200198 1.361676 1.101452 1.187652
 1.121345 1.094482 1.161554 1.360636 1.12618  1.167856 1.081996 1.386154
 1.230143 1.207672 1.187767 1.117737 1.120207 1.124211 1.073078 1.318155
 1.199532 1.253553 0.992412 1.180936 1.126598 1.015179 1.255365 1.253365
 1.260176 1.141428 0.993647 0.985532 1.078126 1.079517 1.347431 1.151275
 1.199374 1.200726 1.318295 1.141931 1.14957  1.023465 1.194518 1.179504
 1.12248  0.908882 1.061184 1.373576 1.083035 1.133783 1.204808 1.034725
 1.233325]
----------------------------------------
Col name: LT_ALL_Dxx_assoc
Data type: float64
Unique values: 209
[0.838976 0.801073 0.921833 0.824179 1.04385  0.817479 1.132849 0.791892
 0.855245 1.156825 1.040997 0.903745 0.787849 0.775191 0.906233 0.799743
 0.632146 0.951714 0.782767 0.858335 0.867577 0.919467 0.719685 0.832461
 0.753924 0.846036 1.255407 0.888593 1.281477 0.885574 0.830649 1.016928
 0.904594 0.801505 1.026453 1.010401 0.717183 0.880957 0.885155 0.81809
 0.990955 0.963625 0.790004 0.928297 1.186851 0.906332 1.059758 0.942335
 0.917875 0.983731 0.979747 0.9333   0.940769 0.99725  0.947076 1.165415
 1.006692 0.806274 0.898562 0.850873 0.894469 0.918098 0.872957 0.81423
 1.13413  0.985183 0.948638 0.785135 0.732054 1.142308 0.995355 0.887617
 0.862724 1.014844 0.856473 0.766374 0.961554 0.997862 0.869926 0.796144
 0.806529 0.852835 0.934288 0.680757 0.885165 0.711826 0.778661 1.140621
 0.856247 1.185462 0.689059 0.875901 0.766804 1.139358 0.82401  0.519688
 0.750454 1.231468 0.769729 0.644696 0.838373 0.976871 0.87463  0.913582
 0.855315 0.871609 0.711879 0.919309 1.191792 0.823551 1.01671  0.917573
 0.761119 0.813292 1.033745 0.851669 0.65651  0.822064 0.823256 0.826074
 0.867975 0.869587 0.980562 0.964868 0.925968 0.915221 0.960323 0.930059
 0.871766 0.75493  0.914381 0.704292 0.772743 0.87245  0.989024 0.834654
 0.974291 0.839412 0.780336 0.910227 0.939582 0.889503 0.745681 1.260075
 0.975437 0.753426 0.907602 0.673688 0.957962 0.911906 0.910703 0.918422
 0.810802 1.298066 0.72403  0.780219 0.767325 0.689703 0.811871 0.949841
 0.709945 0.792752 0.824909 1.0804   0.84812  0.857463 0.808918 0.965197
 0.854568 0.93758  0.845652 0.888594 0.754139 0.733467 0.786659 0.818217
 1.056564 0.806187 0.925783 0.747263 0.822836 0.810267 0.829209 0.964632
 0.987495 0.869121 0.798203 1.149777 0.92123  1.053755 0.964594 1.00318
 0.742082 0.957538 1.022304 0.890171 0.653193 0.81435  0.865598 0.941755
 0.972638 0.859744 0.730744 1.017396 0.980567 0.799426 0.96477  1.054118
 0.774175]
----------------------------------------
Col name: LT_ALL_Dyy_assoc
Data type: float64
Unique values: 209
[1.092285 1.124653 1.174945 0.994313 1.245618 1.012696 1.070788 1.111372
 1.062072 1.231913 1.3492   1.155211 1.019401 1.257166 1.081944 1.030088
 1.064741 1.128002 1.007868 1.102447 0.986188 0.986806 1.036263 0.921122
 1.175664 0.976966 1.345043 1.033081 1.446659 1.25399  1.071612 1.047515
 1.184812 1.029303 1.430111 1.187303 1.045966 1.051864 1.115176 1.110409
 1.200892 1.156169 1.075739 1.187087 1.283007 1.18606  1.241912 1.029773
 1.320642 1.217097 1.178886 0.99395  1.036446 0.952094 1.262267 1.222713
 1.055096 1.075779 1.134696 1.194312 1.049631 1.185011 1.154161 1.118488
 1.259774 1.172744 1.064176 1.139161 1.220206 1.433776 1.273453 1.242271
 1.076538 1.299039 1.113002 0.98321  1.125534 1.274288 1.202416 1.062793
 1.047234 1.231025 1.140748 0.941293 1.18384  1.266497 0.856075 1.265204
 1.118918 1.227039 1.097773 1.101445 1.055847 1.166928 0.895553 0.684828
 1.061202 1.493726 1.145157 1.185012 1.15284  1.144774 1.211957 1.196111
 0.99492  1.067436 1.187508 1.148149 1.351247 1.275065 1.037244 1.0296
 1.051568 1.056257 1.058758 0.78495  1.101994 1.090073 1.076299 1.189661
 1.340311 1.056145 1.142484 1.169068 1.125231 1.09132  1.322028 1.092903
 0.895165 1.043278 1.113467 1.071523 1.227777 1.136501 1.082821 1.134355
 1.043867 1.08979  0.936096 1.121149 1.205323 1.071692 1.178663 1.144298
 1.216299 1.07405  1.034255 1.057587 1.261073 1.281855 1.230181 1.220402
 1.110347 1.045444 0.998872 0.948145 1.252237 1.056053 1.298126 1.227467
 1.219886 0.999128 1.132937 1.270685 1.316283 0.970917 1.096929 1.154592
 1.207507 1.231816 1.051286 1.086016 1.045555 1.01289  1.067521 1.137089
 1.209361 1.100793 1.147235 1.185787 1.058059 0.976246 1.249789 1.210266
 1.191637 1.047765 1.077811 1.032455 1.166439 1.244024 1.115723 1.146188
 1.2148   1.175152 0.938854 1.135228 1.176845 1.17006  1.031168 1.026952
 1.167011 1.166467 0.902089 1.279346 1.264496 1.147285 1.229719 0.944798
 1.059713]
----------------------------------------
Col name: LT_ALL_Dzz_assoc
Data type: float64
Unique values: 209
[0.606418 0.628264 0.667998 0.478768 0.718111 0.557788 0.605129 0.535729
 0.612792 0.626233 0.877985 0.631289 0.486244 0.551411 0.695951 0.477891
 0.44015  0.73054  0.582893 0.589392 0.523164 0.568369 0.493767 0.618127
 0.556969 0.438695 1.076184 0.802274 1.105614 0.687131 0.62431  0.657951
 0.506352 0.791511 0.801012 0.896075 0.392546 0.58218  0.602692 0.586882
 0.692511 0.689121 0.498519 0.737543 0.997766 0.766176 0.830416 0.840773
 0.735951 0.707564 0.55945  0.575082 0.658792 0.704571 0.830014 0.878679
 0.667571 0.62558  0.578805 0.608919 0.680156 0.691683 0.686668 0.591298
 0.793744 0.610555 0.722859 0.483133 0.422743 0.89413  0.703069 0.64996
 0.693131 0.810555 0.685456 0.399237 0.774667 0.614893 0.573706 0.6253
 0.639911 0.662926 0.624386 0.44216  0.609502 0.403062 0.437714 0.856955
 0.492138 0.932793 0.525884 0.629309 0.427463 0.923037 0.608629 0.163693
 0.640388 0.999985 0.553669 0.470195 0.507307 0.670212 0.60636  0.647085
 0.584599 0.698319 0.391551 0.61838  0.923859 0.635352 0.547788 0.698075
 0.561519 0.450345 0.761635 0.625146 0.603671 0.581282 0.438008 0.558304
 0.648371 0.671427 0.676529 0.67478  0.729937 0.61459  0.779487 0.72433
 0.693714 0.631487 0.738312 0.508177 0.522282 0.558714 0.735839 0.446462
 0.651153 0.466665 0.819856 0.587912 0.640603 0.53861  0.665424 0.878416
 0.868599 0.464952 0.679284 0.406156 0.690268 0.616658 0.667262 0.649683
 0.546327 0.907052 0.340982 0.430776 0.559851 0.82859  0.463873 0.654527
 0.492623 0.559436 0.569795 0.74254  0.709592 0.453938 0.529619 0.816484

In [58]:
for df in (dfCN_mgd, dfAD_mgd):
    df.columns = (
        df.columns
          .str.replace('LH-', 'LT_', regex=False)
          .str.replace('RH-', 'RT_', regex=False)
    )
dfCN_mgd

,PDI,PID,DDX,Year,Age,sex,Education_yr,LT_ALL_Dxx_proj,LT_ALL_Dyy_proj,LT_ALL_Dzz_proj,...,EC_RT_ParaHippocampus,HFC_RT_Thalamus,IC_RT_Thalamus,EC_RT_Thalamus,HFC_Whole_CC,IC_Whole_CC,EC_Whole_CC,HFC_Whole_Precuneus,IC_Whole_Precuneus,EC_Whole_Precuneus
0,MWI_CN01_KNH_NODDI32,145616,NL,2019.0,70,F,16.0,0.853582,0.731372,1.259900,...,0.569473,0.826935,0.271682,0.555182,0.596481,0.212770,0.383751,0.628513,0.125133,0.503758
1,MWI_CN04_SSS_NODDI32,2716077,NL,2019.0,62,F,12.0,0.721595,0.654347,1.212313,...,0.489838,0.761443,0.233806,0.527660,0.482623,0.188198,0.294517,0.592590,0.139421,0.453941
2,MWI_CN05_LSS_NODDI32,469852,NL,2019.0,72,M,16.0,0.648850,0.534350,1.036836,...,0.544412,0.850338,0.298828,0.551536,0.560023,0.178677,0.381515,0.707167,0.123957,0.582434
3,MWI_CN06_KDS_NODDI32,2296061,NL,2019.0,72,M,6.0,0.776232,0.855603,0.955848,...,0.573242,1.072521,0.284065,0.788510,0.623203,0.149430,0.473831,0.774144,0.129967,0.644462
4,MWI_CN07_KSB_NODDI32,316024,NL,2019.0,66,M,9.0,0.760503,0.692654,1.243302,...,0.536905,0.884778,0.235095,0.649583,0.540163,0.201650,0.338564,0.664265,0.148808,0.523295
5,MWI_CN09_YKJ_NODDI32,80969,NaMCI,2019.0,65,F,12.0,0.721305,0.585058,1.168966,...,0.545306,0.986288,0.226849,0.759351,0.528989,0.166927,0.362146,0.656091,0.120433,0.535400
6,MWI_CN10_CJS_NODDI32,1147259,Other,2019.0,66,F,9.0,0.766402,0.500861,1.051554,...,0.449067,0.874900,0.364917,0.509969,0.502285,0.193763,0.308677,0.674751,0.154631,0.521590
7,MWI_CN12_LJK_NODDI32,5871888,NL,2019.0,66,F,12.0,0.809517,0.506511,1.159348,...,0.462334,0.860930,0.293146,0.567797,0.561543,0.224490,0.337122,0.663349,0.132673,0.526265
8,MWI_CN13_KH_NODDI32,6476189,SaMCI,2019.0,69,M,16.0,0.661128,0.740881,1.190856,...,0.522063,1.011569,0.237576,0.773883,0.517119,0.085755,0.431430,0.617109,0.129431,0.483453
9,MWI_CN14_PYJ_NODDI32,4341115,NaMCI,2019.0,66,F,0.5,0.667318,0.716731,1.135098,...,0.527500,1.189327,0.276960,0.912264,0.568219,0.154569,0.413899,0.629691,0.130360,0.501892
10,MWI_CN15_YCJ_NODDI32,1607233,Other,2019.0,75,F,6.0,0.783634,0.542104,1.197984,...,0.558958,0.972299,0.285758,0.686471,0.571364,0.164050,0.407373,0.660082,0.112985,0.543710
11,MWI_CN16_LCS_NODDI32,1190888,NaMCI,2019.0,74,M,12.0,0.750492,0.767349,1.155198,...,0.525401,0.972692,0.239256,0.733374,0.567984,0.149137,0.418912,0.704890,0.114604,0.591241
12,MWI_CN17_LPS_NODDI32,4825611,MaMCI,2019.0,63,F,7.0,0.812866,0.996424,1.218665,...,0.480014,0.887022,0.244920,0.642013,0.525424,0.176074,0.349367,0.651993,0.153292,0.501550
13,MWI_CN18_HCS_NODDI32,2022033,MaMCI,2019.0,68,F,6.0,0.805717,0.608529,1.132986,...,0.486360,0.826049,0.303949,0.522080,0.526794,0.191792,0.335063,0.605105,0.134528,0.470944
14,MWI_CN19_CSO_NODDI32,4073053,NL,2019.0,64,F,9.0,0.637047,0.484846,1.023011,...,0.517200,0.867916,0.234691,0.633179,0.473566,0.186737,0.286957,0.652881,0.148644,0.506357
15,MWI_CN20_PYJ_NODDI32,1382411,NL,2020.0,68,M,12.0,0.649847,0.728100,0.978214,...,0.554155,0.865996,0.253210,0.612668,0.566002,0.194978,0.371117,0.668789,0.158707,0.511535
16,MWI_CN21_PYB_NODDI32,4086417,NL,2020.0,66,F,14.0,89.345674,85.156431,85.893714,...,0.463821,0.833821,0.252496,0.581255,0.499714,0.180962,0.318732,0.580333,0.151689,0.433268
17,MWI_CN22_YYJ_NODDI32,875397,NL,2020.0,66,F,16.0,0.771681,0.663884,0.996707,...,0.513835,0.807599,0.227501,0.580202,0.492460,0.184134,0.308399,0.621884,0.129900,0.490079
18,MWI_CN23_HJL_NODDI32,8481071,NL,2020.0,64,F,12.0,0.861621,0.685175,1.368943,...,0.539687,0.925020,0.218422,0.706476,0.469806,0.144857,0.325102,0.593628,0.125361,0.469178
19,MWI_CN24_PKJ_NODDI32,8481058,NL,2020.0,72,M,16.0,0.780769,0.805937,1.189413,...,0.470152,0.945116,0.257279,0.687774,0.453864,0.144097,0.309865,0.666179,0.139076,0.526869
20,MWI_CN25_NKJ_NODDI32,8500417,MaMCI,2020.0,79,F,6.0,0.809053,0.628974,1.200095,...,0.629807,0.956596,0.254913,0.701614,0.634575,0.254143,0.380491,0.701145,0.141241,0.559319
21,MWI_CN26_LSR_NODDI32,8510171,MaMCI,2020.0,69,F,6.0,0.651656,0.516872,1.081359,...,0.462270,0.854853,0.298488,0.556636,0.618233,0.267933,0.350261,0.667676,0.160014,0.509432
22,MWI_CN27_LSJ_NODDI32,8510155,NL,2020.0,68,M,9.0,0.785996,0.609021,1.140311,...,0.501959,0.844196,0.239438,0.604761,0.539841,0.188142,0.351836,0.712939,0.161860,0.556985
23,MWI_CN28_KOS_NODDI32,213101,NL,2020.0,68,F,9.0,0.821979,0.734907,0.993994,...,0.525605,0.852981,0.264995,0.588012,0.550044,0.135748,0.414328,0.672186,0.121256,0.549712
24,MWI_CN29_KSH_NODDI32,243749,SaMCI,2020.0,70,F,12.0,0.652968,0.485778,1.078290,...,0.665788,0.951107,0.317747,0.633336,0.554084,0.151098,0.403054,0.741013,0.150816,0.590936
25,MWI_CN30_PYS_NODDI32,8519137,MaMCI,2020.0,61,F,9.0,0.659945,0.500463,0.978506,...,0.477922,0.836799,0.276130,0.560642,0.485406,0.202200,0.283275,0.625345,0.134644,0.494961
26,MWI_CN31_LOH_NODDI32,2528398,MaMCI,2020.0,75,F,0.0,0.636865,0.624176,1.164440,...,0.497597,0.894365,0.197061,0.697566,0.598659,0.160472,0.438273,0.669564,0.118688,0.554970
27,MWI_CN32_KYH_NODDI32,8664289,SaMCI,2020.0,81,M,9.0,0.696205,0.723061,1.101509,...,0.518186,0.884590,0.273622,0.610941,0.586860,0.148645,0.438361,0.789711,0.150879,0.635681
28,MWI_CN33_LSH_NODDI32,1206895,NL,2020.0,68,F,12.0,0.638877,0.698796,1.098446,...,0.664519,0.911801,0.342418,0.569403,0.516731,0.177462,0.339318,0.643531,0.135235,0.505900
29,MWI_CN34_OJS_NODDI32,4727886,NL,2020.0,77,F,8.0,0.687721,0.524964,1.058712,...,0.551505,1.110993,0.328570,0.782494,0.529869,0.155402,0.374542,0.698818,0.158173,0.541396
30,MWI_CN35_LES_NODDI32,8696493,NL,2020.0,61,F,12.0,0.763828,0.533087,1.089920,...,0.483109,0.737282,0.270293,0.467234,0.530641,0.231312,0.299411,0.644428,0.146404,0.494998
31,MWI_CN36_KER_NODDI32,738146,SaMCI,2020.0,64,F,12.0,0.747137,0.516512,1.174375,...,0.549753,0.842202,0.219193,0.622979,0.518357,0.178988,0.339459,0.626832,0.109305,0.517772
32,MWI_CN37_KJR_NODDI32,1283958,NaMCI,2020.0,65,M,12.0,1.267064,1.244017,1.117839,...,0.454507,0.749496,0.225184,0.524271,0.516256,0.186873,0.329481,0.668951,0.131205,0.540347
33,MWI_CN38_JJB_NODDI32,2022042,NL,2020.0,71,M,3.0,0.697029,0.773143,1.046729,...,0.630026,1.024894,0.292525,0.732272,0.595624,0.129663,0.466013,0.676542,0.109323,0.567562
34,MWI_CN39_LTS_NODDI32,613165,NL,2020.0,77,M,12.0,0.676112,0.748491,1.064096,...,0.507875,0.930561,0.273329,0.657178,0.603205,0.151556,0.451843,0.707243,0.133054,0.575729
35,MWI_CN40_LDS_NODDI32,8129675,NL,2020.0,72,F,12.0,0.680826,0.595489,1.151737,...,0.469159,0.850163,0.383543,0.466574,0.605229,0.194116,0.411091,0.717616,0.147410,0.569150
36,MWI_CN41_JHL_NODDI32,4920375,NL,2020.0,83,F,6.0,0.730996,0.606768,1.137128,...,0.592879,0.840836,0.299190,0.541651,0.623312,0.125874,0.497510,0.775225,0.169911,0.604869
37,MWI_CN57_YHY_NODDI32,8527223,NL,2022.0,76,F,NaN,0.629832,0.574801,0.976331,...,0.508168,0.798943,0.220934,0.578004,0.477151,0.142118,0.335096,0.681972,0.108451,0.580286
38,MWI_CN58_LSB_NODDI32,213324,NL,2022.0,70,M,NaN,0.707732,0.692642,1.101284,...,0.245936,0.840967,0.212460,0.628435,0.535565,0.151260,0.384363,0.636286,0.092683,0.542898
39,MWI_CN61_CHS_NODDI32,1422655,NL,2022.0,76,M,NaN,0.691838,0.513470,1.145116,...,0.518160,0.928442,0.273525,0.655068,0.508125,0.141542,0.366679,0.679949,0.129329,0.544178
40,MWI_CN65_PYS_NODDI32,9524528,NL,2022.0,72,F,NaN,0.742088,0.611022,1.156521,...,0.495931,0.822200,0.190986,0.631176,0.567236,0.182091,0.385219,0.673377,0.123562,0.551009
41,MWI_CN66_CSY_NODDI32,766581,NaMCI,2022.0,71,F,NaN,0.663827,0.725533,1.045238,...,0.436440,0.765378,0.181157,0.584184,0.495296,0.163504,0.331894,0.637991,0.131822,0.508110
42,MWI_CN67_KOS_NODDI32,9577263,NaMCI,2022.0,82,F,NaN,0.625652,0.643337,1.160600,...,0.583334,0.786152,0.203446,0.582679,0.560845,0.146901,0.414069,0.751461,0.115140,0.640286
43,MWI_CN68_CDL_NODDI32,641619,MaMCI,2022.0,74,F,NaN,0.825319,0.661257,1.253624,...,0.546697,0.882832,0.250534,0.632197,0.546445,0.152043,0.394534,0.662188,0.148627,0.512938
44,MWI_CN69_LSL_NODDI32,9588015,NL,2022.0,69,F,NaN,0.567737,0.528092,1.266596,...,0.535490,0.870760,0.208700,0.662040,0.539993,0.129953,0.410144,0.622445,0.123649,0.501116
45,MWI_CN70_LCJ_NODDI32,2202449,NaMCI,2022.0,80,F,NaN,0.771396,0.632500,1.171522,...,0.494867,0.793464,0.218678,0.574741,0.502785,0.165001,0.337965,0.682435,0.120648,0.561929
46,MWI_CN71_LSH_NODDI32,863315,NL,2022.0,73,F,NaN,0.635816,0.511072,1.056698,...,0.629526,0.790673,0.190738,0.600125,0.657349,0.209189,0.448150,0.686114,0.106190,0.578985
47,MWI_CN73_GIS_NODDI32,4074843,MaMCI,2022.0,74,F,NaN,0.614696,0.510977,1.052888,...,0.413912,0.850759,0.284682,0.566028,0.614579,0.217501,0.397129,0.779806,0.171592,0.614299
48,MWI_CN74_LKY_NODDI32,9605724,SaMCI,2022.0,71,F,NaN,0.636038,0.581639,0.989334,...,0.495830,0.807041,0.192684,0.614290,0.540094,0.154422,0.385784,0.672241,0.090988,0.580177
49,MWI_CN75_KKS_NODDI32,9605754,SaMCI,2022.0,73,M,NaN,0.839752,0.745258,1.373741,...,0.457684,0.936529,0.214338,0.722082,0.555994,0.167777,0.388274,0.695768,0.129753,0.565557
50,MWI_CN76_PHJ_NODDI32,359871,NL,2022.0,78,F,NaN,0.974929,0.802987,1.458045,...,0.594984,0.899423,0.214330,0.685096,0.509969,0.174463,0.335585,0.675825,0.164479,0.511178
51,MWI_CN77_PJC_NODDI32,7090169,NL,NaN,68,M,NaN,0.666742,0.643739,1.125764,...,0.434339,0.813729,0.177067,0.636584,0.469045,0.150621,0.318576,0.601623,0.106493,0.492954
52,MWI_CN79_CYE_NODDI32,10412739,SaMCI,2023.0,72,F,NaN,0.753935,0.504262,1.198478,...,0.423002,0.822054,0.257318,0.564671,0.516003,0.183478,0.332622,0.641243,0.138539,0.506524
53,MWI_CN80_LSR_NODDI32,10474812,MaMCI,NaN,78,F,NaN,0.602834,0.559894,1.037194,...,0.753751,0.807771,0.185336,0.622558,0.633271,0.170613,0.462788,0.697514,0.099527,0.591824
54,MWI_CN81_CSH_NODDI32,10482577,SaMCI,2024.0,66,M,NaN,0.638415,0.664246,1.101576,...,0.451643,0.789196,0.212962,0.576243,0.533376,0.141496,0.391933,0.594671,0.095589,0.499690
55,MWI_CN82_LMR_NODDI32,10412747,SaMCI,2023.0,74,M,NaN,0.789849,0.802365,1.201563,...,0.474700,0.901093,0.220515,0.680470,0.488034,0.144081,0.344001,0.621078,0.117980,0.506970
56,MWI_CN83_LYS_NODDI32,10474783,NL,NaN,74,F,NaN,0.572063,0.531833,1.064045,...,0.526787,0.860828,0.222414,0.638332,0.536061,0.155244,0.380953,0.602585,0.118519,0.487089
57,MWI_CN84_LHS_NODDI32,10474798,MaMCI,2024.0,74,F,NaN,0.647483,0.572705,1.053408,...,0.343942,0.769077,0.179261,0.590332,0.535888,0.157677,0.378221,0.599822,0.092429,0.508567

In [61]:
for df in (dfCN_mgd, dfAD_mgd):
    df["PID"] = df["PID"].astype(str).str.zfill(8)
dfCN_mgd

,PDI,PID,DDX,Year,Age,sex,Education_yr,LT_ALL_Dxx_proj,LT_ALL_Dyy_proj,LT_ALL_Dzz_proj,...,EC_RT_ParaHippocampus,HFC_RT_Thalamus,IC_RT_Thalamus,EC_RT_Thalamus,HFC_Whole_CC,IC_Whole_CC,EC_Whole_CC,HFC_Whole_Precuneus,IC_Whole_Precuneus,EC_Whole_Precuneus
0,MWI_CN01_KNH_NODDI32,00145616,NL,2019.0,70,F,16.0,0.853582,0.731372,1.259900,...,0.569473,0.826935,0.271682,0.555182,0.596481,0.212770,0.383751,0.628513,0.125133,0.503758
1,MWI_CN04_SSS_NODDI32,02716077,NL,2019.0,62,F,12.0,0.721595,0.654347,1.212313,...,0.489838,0.761443,0.233806,0.527660,0.482623,0.188198,0.294517,0.592590,0.139421,0.453941
2,MWI_CN05_LSS_NODDI32,00469852,NL,2019.0,72,M,16.0,0.648850,0.534350,1.036836,...,0.544412,0.850338,0.298828,0.551536,0.560023,0.178677,0.381515,0.707167,0.123957,0.582434
3,MWI_CN06_KDS_NODDI32,02296061,NL,2019.0,72,M,6.0,0.776232,0.855603,0.955848,...,0.573242,1.072521,0.284065,0.788510,0.623203,0.149430,0.473831,0.774144,0.129967,0.644462
4,MWI_CN07_KSB_NODDI32,00316024,NL,2019.0,66,M,9.0,0.760503,0.692654,1.243302,...,0.536905,0.884778,0.235095,0.649583,0.540163,0.201650,0.338564,0.664265,0.148808,0.523295
5,MWI_CN09_YKJ_NODDI32,00080969,NaMCI,2019.0,65,F,12.0,0.721305,0.585058,1.168966,...,0.545306,0.986288,0.226849,0.759351,0.528989,0.166927,0.362146,0.656091,0.120433,0.535400
6,MWI_CN10_CJS_NODDI32,01147259,Other,2019.0,66,F,9.0,0.766402,0.500861,1.051554,...,0.449067,0.874900,0.364917,0.509969,0.502285,0.193763,0.308677,0.674751,0.154631,0.521590
7,MWI_CN12_LJK_NODDI32,05871888,NL,2019.0,66,F,12.0,0.809517,0.506511,1.159348,...,0.462334,0.860930,0.293146,0.567797,0.561543,0.224490,0.337122,0.663349,0.132673,0.526265
8,MWI_CN13_KH_NODDI32,06476189,SaMCI,2019.0,69,M,16.0,0.661128,0.740881,1.190856,...,0.522063,1.011569,0.237576,0.773883,0.517119,0.085755,0.431430,0.617109,0.129431,0.483453
9,MWI_CN14_PYJ_NODDI32,04341115,NaMCI,2019.0,66,F,0.5,0.667318,0.716731,1.135098,...,0.527500,1.189327,0.276960,0.912264,0.568219,0.154569,0.413899,0.629691,0.130360,0.501892
10,MWI_CN15_YCJ_NODDI32,01607233,Other,2019.0,75,F,6.0,0.783634,0.542104,1.197984,...,0.558958,0.972299,0.285758,0.686471,0.571364,0.164050,0.407373,0.660082,0.112985,0.543710
11,MWI_CN16_LCS_NODDI32,01190888,NaMCI,2019.0,74,M,12.0,0.750492,0.767349,1.155198,...,0.525401,0.972692,0.239256,0.733374,0.567984,0.149137,0.418912,0.704890,0.114604,0.591241
12,MWI_CN17_LPS_NODDI32,04825611,MaMCI,2019.0,63,F,7.0,0.812866,0.996424,1.218665,...,0.480014,0.887022,0.244920,0.642013,0.525424,0.176074,0.349367,0.651993,0.153292,0.501550
13,MWI_CN18_HCS_NODDI32,02022033,MaMCI,2019.0,68,F,6.0,0.805717,0.608529,1.132986,...,0.486360,0.826049,0.303949,0.522080,0.526794,0.191792,0.335063,0.605105,0.134528,0.470944
14,MWI_CN19_CSO_NODDI32,04073053,NL,2019.0,64,F,9.0,0.637047,0.484846,1.023011,...,0.517200,0.867916,0.234691,0.633179,0.473566,0.186737,0.286957,0.652881,0.148644,0.506357
15,MWI_CN20_PYJ_NODDI32,01382411,NL,2020.0,68,M,12.0,0.649847,0.728100,0.978214,...,0.554155,0.865996,0.253210,0.612668,0.566002,0.194978,0.371117,0.668789,0.158707,0.511535
16,MWI_CN21_PYB_NODDI32,04086417,NL,2020.0,66,F,14.0,89.345674,85.156431,85.893714,...,0.463821,0.833821,0.252496,0.581255,0.499714,0.180962,0.318732,0.580333,0.151689,0.433268
17,MWI_CN22_YYJ_NODDI32,00875397,NL,2020.0,66,F,16.0,0.771681,0.663884,0.996707,...,0.513835,0.807599,0.227501,0.580202,0.492460,0.184134,0.308399,0.621884,0.129900,0.490079
18,MWI_CN23_HJL_NODDI32,08481071,NL,2020.0,64,F,12.0,0.861621,0.685175,1.368943,...,0.539687,0.925020,0.218422,0.706476,0.469806,0.144857,0.325102,0.593628,0.125361,0.469178
19,MWI_CN24_PKJ_NODDI32,08481058,NL,2020.0,72,M,16.0,0.780769,0.805937,1.189413,...,0.470152,0.945116,0.257279,0.687774,0.453864,0.144097,0.309865,0.666179,0.139076,0.526869
20,MWI_CN25_NKJ_NODDI32,08500417,MaMCI,2020.0,79,F,6.0,0.809053,0.628974,1.200095,...,0.629807,0.956596,0.254913,0.701614,0.634575,0.254143,0.380491,0.701145,0.141241,0.559319
21,MWI_CN26_LSR_NODDI32,08510171,MaMCI,2020.0,69,F,6.0,0.651656,0.516872,1.081359,...,0.462270,0.854853,0.298488,0.556636,0.618233,0.267933,0.350261,0.667676,0.160014,0.509432
22,MWI_CN27_LSJ_NODDI32,08510155,NL,2020.0,68,M,9.0,0.785996,0.609021,1.140311,...,0.501959,0.844196,0.239438,0.604761,0.539841,0.188142,0.351836,0.712939,0.161860,0.556985
23,MWI_CN28_KOS_NODDI32,00213101,NL,2020.0,68,F,9.0,0.821979,0.734907,0.993994,...,0.525605,0.852981,0.264995,0.588012,0.550044,0.135748,0.414328,0.672186,0.121256,0.549712
24,MWI_CN29_KSH_NODDI32,00243749,SaMCI,2020.0,70,F,12.0,0.652968,0.485778,1.078290,...,0.665788,0.951107,0.317747,0.633336,0.554084,0.151098,0.403054,0.741013,0.150816,0.590936
25,MWI_CN30_PYS_NODDI32,08519137,MaMCI,2020.0,61,F,9.0,0.659945,0.500463,0.978506,...,0.477922,0.836799,0.276130,0.560642,0.485406,0.202200,0.283275,0.625345,0.134644,0.494961
26,MWI_CN31_LOH_NODDI32,02528398,MaMCI,2020.0,75,F,0.0,0.636865,0.624176,1.164440,...,0.497597,0.894365,0.197061,0.697566,0.598659,0.160472,0.438273,0.669564,0.118688,0.554970
27,MWI_CN32_KYH_NODDI32,08664289,SaMCI,2020.0,81,M,9.0,0.696205,0.723061,1.101509,...,0.518186,0.884590,0.273622,0.610941,0.586860,0.148645,0.438361,0.789711,0.150879,0.635681
28,MWI_CN33_LSH_NODDI32,01206895,NL,2020.0,68,F,12.0,0.638877,0.698796,1.098446,...,0.664519,0.911801,0.342418,0.569403,0.516731,0.177462,0.339318,0.643531,0.135235,0.505900
29,MWI_CN34_OJS_NODDI32,04727886,NL,2020.0,77,F,8.0,0.687721,0.524964,1.058712,...,0.551505,1.110993,0.328570,0.782494,0.529869,0.155402,0.374542,0.698818,0.158173,0.541396
30,MWI_CN35_LES_NODDI32,08696493,NL,2020.0,61,F,12.0,0.763828,0.533087,1.089920,...,0.483109,0.737282,0.270293,0.467234,0.530641,0.231312,0.299411,0.644428,0.146404,0.494998
31,MWI_CN36_KER_NODDI32,00738146,SaMCI,2020.0,64,F,12.0,0.747137,0.516512,1.174375,...,0.549753,0.842202,0.219193,0.622979,0.518357,0.178988,0.339459,0.626832,0.109305,0.517772
32,MWI_CN37_KJR_NODDI32,01283958,NaMCI,2020.0,65,M,12.0,1.267064,1.244017,1.117839,...,0.454507,0.749496,0.225184,0.524271,0.516256,0.186873,0.329481,0.668951,0.131205,0.540347
33,MWI_CN38_JJB_NODDI32,02022042,NL,2020.0,71,M,3.0,0.697029,0.773143,1.046729,...,0.630026,1.024894,0.292525,0.732272,0.595624,0.129663,0.466013,0.676542,0.109323,0.567562
34,MWI_CN39_LTS_NODDI32,00613165,NL,2020.0,77,M,12.0,0.676112,0.748491,1.064096,...,0.507875,0.930561,0.273329,0.657178,0.603205,0.151556,0.451843,0.707243,0.133054,0.575729
35,MWI_CN40_LDS_NODDI32,08129675,NL,2020.0,72,F,12.0,0.680826,0.595489,1.151737,...,0.469159,0.850163,0.383543,0.466574,0.605229,0.194116,0.411091,0.717616,0.147410,0.569150
36,MWI_CN41_JHL_NODDI32,04920375,NL,2020.0,83,F,6.0,0.730996,0.606768,1.137128,...,0.592879,0.840836,0.299190,0.541651,0.623312,0.125874,0.497510,0.775225,0.169911,0.604869
37,MWI_CN57_YHY_NODDI32,08527223,NL,2022.0,76,F,NaN,0.629832,0.574801,0.976331,...,0.508168,0.798943,0.220934,0.578004,0.477151,0.142118,0.335096,0.681972,0.108451,0.580286
38,MWI_CN58_LSB_NODDI32,00213324,NL,2022.0,70,M,NaN,0.707732,0.692642,1.101284,...,0.245936,0.840967,0.212460,0.628435,0.535565,0.151260,0.384363,0.636286,0.092683,0.542898
39,MWI_CN61_CHS_NODDI32,01422655,NL,2022.0,76,M,NaN,0.691838,0.513470,1.145116,...,0.518160,0.928442,0.273525,0.655068,0.508125,0.141542,0.366679,0.679949,0.129329,0.544178
40,MWI_CN65_PYS_NODDI32,09524528,NL,2022.0,72,F,NaN,0.742088,0.611022,1.156521,...,0.495931,0.822200,0.190986,0.631176,0.567236,0.182091,0.385219,0.673377,0.123562,0.551009
41,MWI_CN66_CSY_NODDI32,00766581,NaMCI,2022.0,71,F,NaN,0.663827,0.725533,1.045238,...,0.436440,0.765378,0.181157,0.584184,0.495296,0.163504,0.331894,0.637991,0.131822,0.508110
42,MWI_CN67_KOS_NODDI32,09577263,NaMCI,2022.0,82,F,NaN,0.625652,0.643337,1.160600,...,0.583334,0.786152,0.203446,0.582679,0.560845,0.146901,0.414069,0.751461,0.115140,0.640286
43,MWI_CN68_CDL_NODDI32,00641619,MaMCI,2022.0,74,F,NaN,0.825319,0.661257,1.253624,...,0.546697,0.882832,0.250534,0.632197,0.546445,0.152043,0.394534,0.662188,0.148627,0.512938
44,MWI_CN69_LSL_NODDI32,09588015,NL,2022.0,69,F,NaN,0.567737,0.528092,1.266596,...,0.535490,0.870760,0.208700,0.662040,0.539993,0.129953,0.410144,0.622445,0.123649,0.501116
45,MWI_CN70_LCJ_NODDI32,02202449,NaMCI,2022.0,80,F,NaN,0.771396,0.632500,1.171522,...,0.494867,0.793464,0.218678,0.574741,0.502785,0.165001,0.337965,0.682435,0.120648,0.561929
46,MWI_CN71_LSH_NODDI32,00863315,NL,2022.0,73,F,NaN,0.635816,0.511072,1.056698,...,0.629526,0.790673,0.190738,0.600125,0.657349,0.209189,0.448150,0.686114,0.106190,0.578985
47,MWI_CN73_GIS_NODDI32,04074843,MaMCI,2022.0,74,F,NaN,0.614696,0.510977,1.052888,...,0.413912,0.850759,0.284682,0.566028,0.614579,0.217501,0.397129,0.779806,0.171592,0.614299
48,MWI_CN74_LKY_NODDI32,09605724,SaMCI,2022.0,71,F,NaN,0.636038,0.581639,0.989334,...,0.495830,0.807041,0.192684,0.614290,0.540094,0.154422,0.385784,0.672241,0.090988,0.580177
49,MWI_CN75_KKS_NODDI32,09605754,SaMCI,2022.0,73,M,NaN,0.839752,0.745258,1.373741,...,0.457684,0.936529,0.214338,0.722082,0.555994,0.167777,0.388274,0.695768,0.129753,0.565557
50,MWI_CN76_PHJ_NODDI32,00359871,NL,2022.0,78,F,NaN,0.974929,0.802987,1.458045,...,0.594984,0.899423,0.214330,0.685096,0.509969,0.174463,0.335585,0.675825,0.164479,0.511178
51,MWI_CN77_PJC_NODDI32,07090169,NL,NaN,68,M,NaN,0.666742,0.643739,1.125764,...,0.434339,0.813729,0.177067,0.636584,0.469045,0.150621,0.318576,0.601623,0.106493,0.492954
52,MWI_CN79_CYE_NODDI32,10412739,SaMCI,2023.0,72,F,NaN,0.753935,0.504262,1.198478,...,0.423002,0.822054,0.257318,0.564671,0.516003,0.183478,0.332622,0.641243,0.138539,0.506524
53,MWI_CN80_LSR_NODDI32,10474812,MaMCI,NaN,78,F,NaN,0.602834,0.559894,1.037194,...,0.753751,0.807771,0.185336,0.622558,0.633271,0.170613,0.462788,0.697514,0.099527,0.591824
54,MWI_CN81_CSH_NODDI32,10482577,SaMCI,2024.0,66,M,NaN,0.638415,0.664246,1.101576,...,0.451643,0.789196,0.212962,0.576243,0.533376,0.141496,0.391933,0.594671,0.095589,0.499690
55,MWI_CN82_LMR_NODDI32,10412747,SaMCI,2023.0,74,M,NaN,0.789849,0.802365,1.201563,...,0.474700,0.901093,0.220515,0.680470,0.488034,0.144081,0.344001,0.621078,0.117980,0.506970
56,MWI_CN83_LYS_NODDI32,10474783,NL,NaN,74,F,NaN,0.572063,0.531833,1.064045,...,0.526787,0.860828,0.222414,0.638332,0.536061,0.155244,0.380953,0.602585,0.118519,0.487089
57,MWI_CN84_LHS_NODDI32,10474798,MaMCI,2024.0,74,F,NaN,0.647483,0.572705,1.053408,...,0.343942,0.769077,0.179261,0.590332,0.535888,0.157677,0.378221,0.599822,0.092429,0.508567

In [62]:
dfAD_mgd

,PDI,PID,DDX,Year,Age,sex,Education_yr,LT_ALL_Dxx_proj,LT_ALL_Dyy_proj,LT_ALL_Dzz_proj,...,EC_RT_ParaHippocampus,HFC_RT_Thalamus,IC_RT_Thalamus,EC_RT_Thalamus,HFC_Whole_CC,IC_Whole_CC,EC_Whole_CC,HFC_Whole_Precuneus,IC_Whole_Precuneus,EC_Whole_Precuneus
0,MREPT2019AD01_KMO_NODDI32,03735478,MaMCI,2019,70.0,F,14.0,0.644891,0.617538,1.173563,...,0.574908,0.836188,0.269571,0.567105,0.589605,0.171864,0.417809,0.673767,0.123427,0.55042
1,MREPT2019AD02_JSJ_NODDI32,04381137,SaMCI,2019,68.0,F,13.0,0.711342,0.473727,1.183256,...,0.523015,0.743879,0.262853,0.481046,0.500492,0.165644,0.334925,0.598505,0.142315,0.457942
2,MREPT2019AD03_OHS_NODDI32,04452316,Other,2019,67.0,F,9.0,0.817484,0.701432,1.253393,...,0.519948,0.885777,0.26201,0.623679,0.528768,0.164828,0.364057,0.579572,0.12915,0.450615
3,MREPT2019AD04_CSY_NODDI32,04681566,Other,2019,66.0,M,12.0,0.636522,0.566616,1.020413,...,0.449734,0.751123,0.223271,0.527847,0.543459,0.2151,0.328426,0.657526,0.129952,0.529767
4,MREPT2019AD05_KJI_NODDI32,07205823,SaMCI,2019,77.0,F,6.0,0.884875,0.763448,1.324970,...,0.516597,0.906839,0.22427,0.682516,0.653884,0.16927,0.484581,0.722335,0.141361,0.584527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,EPT2024AD09_CSO_NODDI32,05212646,Other,2024,79.0,F,NaN,0.777790,0.751147,1.083035,...,0.592709,0.793156,0.242145,0.551257,0.59785,0.143183,0.454816,0.770251,0.122816,0.650285
205,EPT2024AD10_KCJ_NODDI32,07295104,Other,2024,77.0,F,NaN,0.703165,0.449837,1.133783,...,0.360986,0.740868,0.237083,0.503703,0.536423,0.194904,0.341641,0.634578,0.122864,0.507875
206,EPT2024AD11_KHJ_NODDI32,07760856,Other,2024,70.0,F,NaN,0.695299,0.652078,1.204808,...,0.459306,0.886238,0.212521,0.67383,0.583785,0.140967,0.44292,0.638426,0.118866,0.519198
207,EPT2024AD12_LDS_NODDI32,10130501,AD,2024,58.0,M,NaN,0.758654,0.879287,1.034725,...,0.650494,0.910185,0.255858,0.65449,0.624966,0.152604,0.472451,0.771421,0.119155,0.65466
208,EPT2024AD13_LTO_NODDI32,10466131,Other,2024,77.0,F,NaN,0.672885,0.600487,1.233325,...,0.296273,0.809635,0.211624,0.597973,0.638725,0.148933,0.490039,0.712426,0.095413,0.61856

In [64]:
with pd.ExcelWriter(os.path.join(ALPS_DIR, "Auto_ALPS_index_19-24_0731.xlsx")
                    , engine='openpyxl') as writer:
    dfCN_mgd.to_excel(writer, sheet_name='CN',       index=False)
    dfAD_mgd.to_excel(writer, sheet_name='Dementia', index=False)